plugins {
    id("conventions.preset.base")
    // id("dev.hsbrysk.kuery-client") version "0.4.0-SNAPSHOT"
}

// Mirrored by ../functional-test-auto-trim/build.gradle.kts (same setup plus the autoTrimIndent
// plugin option) — keep the two build scripts in sync.
description = "Kuery client's compiler functional test module."

dependencies {
    implementation(projects.kueryClientCore)
    kotlinCompilerPluginClasspath(projects.kueryClientCompiler)
    // core exposes coroutines as compileOnly; implementing KueryClient (Flow in its signatures)
    // and driving suspend call sites (runBlocking) in tests needs it on the test classpath.
    testImplementation(libs.kotlin.coroutines.core)
}

kotlin {
    compilerOptions {
        // Guard against IR consistency violations (e.g. sharing a single node between
        // two parents) in the IR generated by kuery-client-compiler.
        freeCompilerArgs.add("-Xverify-ir=error")
    }
}
