plugins {
    id("conventions.preset.base")
    // id("dev.hsbrysk.kuery-client") version "0.4.0-SNAPSHOT"
}

description = "Kuery client's compiler functional test module."

dependencies {
    implementation(projects.kueryClientCore)
    kotlinCompilerPluginClasspath(projects.kueryClientCompiler)
}

kotlin {
    compilerOptions {
        // Guard against IR consistency violations (e.g. sharing a single node between
        // two parents) in the IR generated by kuery-client-compiler.
        freeCompilerArgs.add("-Xverify-ir=error")
    }
}
