package dev.hsbrysk.kuery.spring.jdbc.mapping

import assertk.assertFailure
import assertk.assertThat
import assertk.assertions.isEqualTo
import assertk.assertions.isInstanceOf
import dev.hsbrysk.kuery.core.single
import dev.hsbrysk.kuery.spring.jdbc.H2TestDatabase
import org.junit.jupiter.api.AfterEach
import org.junit.jupiter.api.BeforeEach
import org.junit.jupiter.api.Test
import org.springframework.jdbc.BadSqlGrammarException

class DataClassColumnMismatchTest {
    private val kueryClient = h2.kueryClient()

    @BeforeEach
    fun beforeEach() {
        h2.jdbcClient.sql(
            """
            CREATE TABLE person
            (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                name VARCHAR(255) NOT NULL,
                nickname VARCHAR(255) DEFAULT NULL
            )
            """.trimIndent(),
        ).update()
        h2.jdbcClient.sql("INSERT INTO person (name, nickname) VALUES ('alice', 'ali')").update()
    }

    @AfterEach
    fun afterEach() {
        h2.jdbcClient.sql("DROP TABLE person").update()
    }

    data class NameOnly(val name: String)

    data class NameAndNickname(
        val name: String,
        val nickname: String?,
    )

    @Test
    fun `extra selected columns absent from the data class are ignored`() {
        val record: NameOnly = kueryClient.sql { +"SELECT * FROM person" }.single()
        assertThat(record).isEqualTo(NameOnly("alice"))
    }

    @Test
    fun `a missing column for a constructor parameter throws even if the property is nullable`() {
        // BadSqlGrammarException looks odd for a mapping problem, but it is consistent across
        // drivers (verified against MySQL too, not just H2): DataClassRowMapper resolves each
        // constructor parameter via ResultSet.findColumn, drivers report an unknown column as
        // SQLState class 42 (42S22, the same class as a typo'd column in SQL text), and Spring's
        // exception translation maps that class to BadSqlGrammarException.
        // The r2dbc module reports the same mismatch as DataRetrievalFailureException instead.
        assertFailure {
            kueryClient.sql { +"SELECT name FROM person" }.single(NameAndNickname::class)
        }.isInstanceOf(BadSqlGrammarException::class)
    }

    companion object {
        private val h2 = H2TestDatabase()
    }
}
