package dev.hsbrysk.kuery.spring.jdbc.mapping

import assertk.assertThat
import assertk.assertions.isEqualTo
import dev.hsbrysk.kuery.spring.jdbc.H2TestDatabase
import org.junit.jupiter.api.AfterEach
import org.junit.jupiter.api.BeforeEach
import org.junit.jupiter.api.Test

/**
 * Note the jdbc/r2dbc divergence: spring-jdbc's ColumnMapRowMapper keeps the FIRST occurrence of a
 * duplicated label, while spring-r2dbc's column map keeps the LAST. Alias duplicated columns
 * explicitly when joining tables that share column names.
 */
class DuplicateColumnLabelTest {
    private val kueryClient = h2.kueryClient()

    @BeforeEach
    fun beforeEach() {
        h2.jdbcClient.sql(
            """
            CREATE TABLE person
            (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                name VARCHAR(255) NOT NULL,
                company_id BIGINT NOT NULL
            )
            """.trimIndent(),
        ).update()
        h2.jdbcClient.sql(
            """
            CREATE TABLE company
            (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                name VARCHAR(255) NOT NULL
            )
            """.trimIndent(),
        ).update()
        h2.jdbcClient.sql("INSERT INTO company (id, name) VALUES (1, 'acme')").update()
        h2.jdbcClient.sql("INSERT INTO person (name, company_id) VALUES ('alice', 1)").update()
    }

    @AfterEach
    fun afterEach() {
        h2.jdbcClient.sql("DROP TABLE person").update()
        h2.jdbcClient.sql("DROP TABLE company").update()
    }

    @Test
    fun `singleMap keeps the first value when a join produces duplicate column labels`() {
        val record = kueryClient.sql {
            +"""
            SELECT person.name, company.name
            FROM person
            JOIN company ON person.company_id = company.id
            """.trimIndent()
        }.singleMap()

        assertThat(record["name"]).isEqualTo("alice")
    }

    companion object {
        private val h2 = H2TestDatabase()
    }
}
