package dev.hsbrysk.kuery.spring.testing.contract.conversion

import dev.hsbrysk.kuery.core.KueryClient
import dev.hsbrysk.kuery.spring.testing.ContractDatabase
import org.junit.jupiter.api.AfterEach
import org.junit.jupiter.api.BeforeEach

/**
 * Base for the conversion contracts, which all exercise the single-column `converter` table.
 * The table DDL lives here rather than on [ContractDatabase] to keep that interface minimal.
 */
abstract class ConverterContractBase {
    protected abstract val database: ContractDatabase

    /** Converters registered on [kueryClient]. Contracts with a fixed converter set override this. */
    protected open val converters: List<Any> get() = emptyList()

    // lazy: `database` is not resolvable yet while this base class initializes.
    protected val kueryClient: KueryClient by lazy { database.kueryClient(converters) }

    @BeforeEach
    fun setUpConverterTable() {
        database.execute(
            """
            CREATE TABLE converter
            (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                text VARCHAR(255) DEFAULT NULL
            )
            """.trimIndent(),
        )
    }

    @AfterEach
    fun dropConverterTable() {
        database.execute("DROP TABLE converter")
    }
}
