plugins {
    id("conventions.preset.base")
}

description = "Kuery client's compiler functional test module with autoTrimIndent enabled."

dependencies {
    implementation(projects.kueryClientCore)
    kotlinCompilerPluginClasspath(projects.kueryClientCompiler)
}

kotlin {
    compilerOptions {
        // Guard against IR consistency violations (e.g. sharing a single node between
        // two parents) in the IR generated by kuery-client-compiler.
        freeCompilerArgs.add("-Xverify-ir=error")
        freeCompilerArgs.addAll("-P", "plugin:dev.hsbrysk.kuery-client:autoTrimIndent=true")
    }
}
