package dev.hsbrysk.kuery.compiler.ir

import org.jetbrains.kotlin.backend.common.IrElementTransformerVoidWithContext
import org.jetbrains.kotlin.backend.common.extensions.IrPluginContext
import org.jetbrains.kotlin.backend.common.lower.DeclarationIrBuilder
import org.jetbrains.kotlin.cli.common.messages.CompilerMessageSeverity
import org.jetbrains.kotlin.cli.common.messages.MessageCollector
import org.jetbrains.kotlin.descriptors.DescriptorVisibilities
import org.jetbrains.kotlin.ir.builders.declarations.addValueParameter
import org.jetbrains.kotlin.ir.builders.declarations.buildFun
import org.jetbrains.kotlin.ir.builders.irBlockBody
import org.jetbrains.kotlin.ir.builders.irCall
import org.jetbrains.kotlin.ir.builders.irCallConstructor
import org.jetbrains.kotlin.ir.builders.irGet
import org.jetbrains.kotlin.ir.builders.irReturn
import org.jetbrains.kotlin.ir.builders.irString
import org.jetbrains.kotlin.ir.declarations.IrClass
import org.jetbrains.kotlin.ir.declarations.IrConstructor
import org.jetbrains.kotlin.ir.declarations.IrDeclarationOrigin
import org.jetbrains.kotlin.ir.declarations.IrParameterKind
import org.jetbrains.kotlin.ir.declarations.IrSimpleFunction
import org.jetbrains.kotlin.ir.declarations.IrValueParameter
import org.jetbrains.kotlin.ir.expressions.IrCall
import org.jetbrains.kotlin.ir.expressions.IrClassReference
import org.jetbrains.kotlin.ir.expressions.IrExpression
import org.jetbrains.kotlin.ir.expressions.IrStatementOrigin
import org.jetbrains.kotlin.ir.expressions.impl.IrFunctionExpressionImpl
import org.jetbrains.kotlin.ir.symbols.IrClassSymbol
import org.jetbrains.kotlin.ir.symbols.IrSimpleFunctionSymbol
import org.jetbrains.kotlin.ir.types.IrSimpleType
import org.jetbrains.kotlin.ir.types.classFqName
import org.jetbrains.kotlin.ir.types.classOrNull
import org.jetbrains.kotlin.ir.types.makeNullable
import org.jetbrains.kotlin.ir.types.typeWith
import org.jetbrains.kotlin.ir.util.fqNameWhenAvailable
import org.jetbrains.kotlin.ir.util.functions
import org.jetbrains.kotlin.ir.util.isNullable
import org.jetbrains.kotlin.ir.util.parentAsClass
import org.jetbrains.kotlin.ir.util.parentClassOrNull
import org.jetbrains.kotlin.ir.util.primaryConstructor
import org.jetbrains.kotlin.name.CallableId
import org.jetbrains.kotlin.name.ClassId
import org.jetbrains.kotlin.name.FqName
import org.jetbrains.kotlin.name.Name
import org.jetbrains.kotlin.name.SpecialNames

/**
 * PoC (sqlx4k backend exploration): synthesizes a row-mapping lambda at the call site of
 * `Sqlx4kFetchSpec.single<T>()` / `singleOrNull<T>()` / `list<T>()` and rewrites the call to the
 * corresponding `(ResultSet.Row) -> T` overload.
 *
 * `client.sql { ... }.list<User>()` therefore needs no annotation, no KSP, and no reflection:
 * the mapper (`User(id = row.get("id").asInt(), ...)`) is generated by the compiler plugin from
 * the reified type argument, with snake_case column-name conversion. Without the plugin the
 * marker functions throw at runtime, mirroring the `add`/`unaryPlus` design.
 *
 * Both call shapes are recognized: the reified no-arg wrapper (seen when this pass runs before
 * inlining) and the `KClass` marker with a literal `T::class` argument (seen if the wrapper was
 * already inlined).
 */
@Suppress("OPT_IN_USAGE")
class RowMapperSynthesisTransformer(
    private val pluginContext: IrPluginContext,
    private val messageCollector: MessageCollector,
) : IrElementTransformerVoidWithContext() {
    override fun visitCall(expression: IrCall): IrExpression {
        if (!expression.isAutoMapperCall()) {
            return super.visitCall(expression)
        }
        expression.transformChildren(this, null)

        // Not statically determinable (e.g. the reified wrappers' own `T::class` bodies, or a
        // generic passthrough) — leave the call as is; it only fails at runtime if actually hit.
        val recordType = expression.recordTypeOrNull() ?: return expression
        return rewrittenCallOrNull(expression, recordType) ?: expression
    }

    /** The rewritten call, or null (after reporting an error) when the record type is unusable. */
    private fun rewrittenCallOrNull(
        expression: IrCall,
        recordType: IrSimpleType,
    ): IrExpression? {
        val recordClass = recordType.classOrNull?.owner
        if (recordClass == null || !recordClass.isData) {
            report(expression, "the type argument must be a data class, but was ${recordType.classFqName}")
            return null
        }
        val constructor = checkNotNull(recordClass.primaryConstructor)
        // Validate every property upfront so that on failure the IR is left completely untouched.
        val constructorParameters = constructor.parameters.filter { it.kind == IrParameterKind.Regular }
        val decoderNames = decoderNamesOrNull(expression, constructorParameters) ?: return null

        val rowClass = checkNotNull(pluginContext.finderForBuiltins().findClass(ROW)) {
            "sqlx4k is not on the compile classpath"
        }
        val mapperExpression = mapperExpression(expression, recordType, rowClass, constructor, decoderNames)

        val overload = expression.symbol.owner.parentAsClass.mapperOverload(expression.symbol.owner.name)
        val resultType = when (expression.symbol.owner.name.asString()) {
            "single" -> recordType
            "singleOrNull" -> recordType.makeNullable()
            else -> pluginContext.irBuiltIns.listClass.typeWith(recordType)
        }
        val builder = DeclarationIrBuilder(
            pluginContext,
            checkNotNull(currentScope).scope.scopeOwnerSymbol,
            expression.startOffset,
            expression.endOffset,
        )
        return builder.irCall(overload, resultType).apply {
            dispatchReceiver = expression.dispatchReceiver
            typeArguments[0] = recordType
            val mapperParameter = overload.owner.parameters.first { it.kind == IrParameterKind.Regular }
            arguments[mapperParameter] = mapperExpression
        }
    }

    private fun decoderNamesOrNull(
        expression: IrCall,
        constructorParameters: List<IrValueParameter>,
    ): List<String>? = constructorParameters.map { parameter ->
        val base = SCALAR_DECODERS[parameter.type.classFqName?.asString()]
        if (base == null) {
            report(
                expression,
                "unsupported property type ${parameter.type.classFqName} for " +
                    "'${parameter.name}' (the PoC supports basic scalars only)",
            )
            return null
        }
        if (parameter.type.isNullable()) "${base}OrNull" else base
    }

    /** `fun (row: Row): T = T(<property> = row.get("<snake_case>").<decoder>(), ...)` */
    private fun mapperExpression(
        expression: IrCall,
        recordType: IrSimpleType,
        rowClass: IrClassSymbol,
        constructor: IrConstructor,
        decoderNames: List<String>,
    ): IrExpression {
        val rowType = rowClass.typeWith()
        val constructorParameters = constructor.parameters.filter { it.kind == IrParameterKind.Regular }
        val lambda = pluginContext.irFactory.buildFun {
            origin = IrDeclarationOrigin.LOCAL_FUNCTION_FOR_LAMBDA
            name = SpecialNames.ANONYMOUS
            visibility = DescriptorVisibilities.LOCAL
            returnType = recordType
            startOffset = expression.startOffset
            endOffset = expression.endOffset
        }.apply {
            parent = checkNotNull(currentDeclarationParent)
            val rowParameter = addValueParameter("row", rowType)
            val lambdaBuilder =
                DeclarationIrBuilder(pluginContext, symbol, expression.startOffset, expression.endOffset)
            body = lambdaBuilder.irBlockBody {
                val constructorCall = irCallConstructor(constructor.symbol, emptyList()).apply {
                    constructorParameters.forEachIndexed { index, parameter ->
                        arguments[parameter] = decodedColumn(
                            lambdaBuilder,
                            rowClass,
                            irGet(rowParameter),
                            parameter.name.asString(),
                            decoderNames[index],
                        )
                    }
                }
                +irReturn(constructorCall)
            }
        }
        return IrFunctionExpressionImpl(
            expression.startOffset,
            expression.endOffset,
            pluginContext.irBuiltIns.functionN(1).typeWith(rowType, recordType),
            lambda,
            IrStatementOrigin.LAMBDA,
        )
    }

    /**
     * `row.get("<column>")` followed by the decoder: member `asString[OrNull]()` for strings,
     * the `impl.extensions` `asXxx[OrNull]()` extension for the other scalars.
     */
    private fun decodedColumn(
        builder: DeclarationIrBuilder,
        rowClass: IrClassSymbol,
        row: IrExpression,
        propertyName: String,
        decoderName: String,
    ): IrExpression {
        val get = rowClass.functions.first { function ->
            function.owner.name.asString() == "get" &&
                function.owner.parameters.singleOrNull { it.kind == IrParameterKind.Regular }
                    ?.type?.classFqName?.asString() == "kotlin.String"
        }
        val column = builder.irCall(get).apply {
            dispatchReceiver = row
            arguments[get.owner.parameters.first { it.kind == IrParameterKind.Regular }] =
                builder.irString(propertyName.toSnakeCase())
        }

        val columnClass = checkNotNull(pluginContext.finderForBuiltins().findClass(COLUMN))
        val member = columnClass.functions.singleOrNull { it.owner.name.asString() == decoderName }
        if (member != null) {
            return builder.irCall(member).apply { dispatchReceiver = column }
        }
        val extension = pluginContext.finderForBuiltins()
            .findFunctions(CallableId(EXTENSIONS_PACKAGE, Name.identifier(decoderName)))
            .single()
        return builder.irCall(extension).apply {
            arguments[extension.owner.parameters.first { it.kind == IrParameterKind.ExtensionReceiver }] = column
        }
    }

    /**
     * The concrete record type: the reified type argument of the no-arg wrapper, or the class of
     * a literal `T::class` argument of the `KClass` marker. Null when it cannot be determined
     * statically (e.g. a still-generic passthrough).
     */
    private fun IrCall.recordTypeOrNull(): IrSimpleType? {
        val fromTypeArgument = typeArguments.getOrNull(0) as? IrSimpleType
        if (symbol.owner.hasNoRegularParameters()) {
            return fromTypeArgument?.takeIf { it.classOrNull != null }
        }
        val argument = arguments[symbol.owner.parameters.first { it.kind == IrParameterKind.Regular }]
        return ((argument as? IrClassReference)?.classType as? IrSimpleType)?.takeIf { it.classOrNull != null }
    }

    private fun IrClass.mapperOverload(name: Name): IrSimpleFunctionSymbol = functions.first { function ->
        function.name == name &&
            function.parameters.singleOrNull { it.kind == IrParameterKind.Regular }
                ?.type?.classFqName?.asString() == "kotlin.Function1"
    }.symbol

    private fun report(
        expression: IrCall,
        message: String,
    ) {
        messageCollector.report(
            CompilerMessageSeverity.ERROR,
            "kuery-client row-mapper synthesis (PoC): $message " +
                "(at ${expression.symbol.owner.name.asString()} call)",
        )
    }

    companion object {
        private val SQLX4K_PACKAGE = FqName("io.github.smyrgeorge.sqlx4k")
        private val EXTENSIONS_PACKAGE = FqName("io.github.smyrgeorge.sqlx4k.impl.extensions")
        private val ROW = ClassId(SQLX4K_PACKAGE, FqName("ResultSet.Row"), false)
        private val COLUMN = ClassId(SQLX4K_PACKAGE, FqName("ResultSet.Row.Column"), false)

        // PoC: the FQN of the sqlx4k-backend fetch spec lives in the kmp-poc module for now.
        private const val FETCH_SPEC = "dev.hsbrysk.kuery.sqlx4k.Sqlx4kFetchSpec"
        private val MARKER_NAMES = setOf("single", "singleOrNull", "list")

        private val SCALAR_DECODERS = mapOf(
            "kotlin.String" to "asString",
            "kotlin.Int" to "asInt",
            "kotlin.Long" to "asLong",
            "kotlin.Short" to "asShort",
            "kotlin.Boolean" to "asBoolean",
            "kotlin.Double" to "asDouble",
            "kotlin.Float" to "asFloat",
        )

        private fun IrCall.isAutoMapperCall(): Boolean {
            val function = symbol.owner
            if (function.name.asString() !in MARKER_NAMES) return false
            if (function.parentClassOrNull?.fqNameWhenAvailable?.asString() != FETCH_SPEC) return false
            // The no-arg reified wrapper, or the KClass marker — never the mapper overloads.
            return function.hasNoRegularParameters() ||
                function.parameters.singleOrNull { it.kind == IrParameterKind.Regular }
                    ?.type?.classFqName?.asString() == "kotlin.reflect.KClass"
        }

        private fun IrSimpleFunction.hasNoRegularParameters(): Boolean =
            parameters.none { it.kind == IrParameterKind.Regular }

        private fun String.toSnakeCase(): String =
            replace(Regex("([a-z0-9])([A-Z])")) { "${it.groupValues[1]}_${it.groupValues[2]}" }.lowercase()
    }
}
