package dev.hsbrysk.kuery.spring.jdbc.usage

import assertk.assertThat
import assertk.assertions.hasSize
import dev.hsbrysk.kuery.spring.jdbc.H2TestDatabase
import org.junit.jupiter.api.AfterEach
import org.junit.jupiter.api.BeforeEach
import org.junit.jupiter.api.Test

class StatementOptionsTest {
    private val kueryClient = h2.kueryClient()

    @BeforeEach
    fun setUp() {
        h2.jdbcClient.sql(
            """
            CREATE TABLE users (
                user_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                username VARCHAR(50) NOT NULL,
                email VARCHAR(100) NOT NULL
            )
            """.trimIndent(),
        ).update()
        repeat(10) { i ->
            h2.jdbcClient.sql("INSERT INTO users (username, email) VALUES ('user$i', 'user$i@example.com')").update()
        }
    }

    @AfterEach
    fun tearDown() {
        h2.jdbcClient.sql("DROP TABLE users").update()
    }

    @Test
    fun `fetchSize does not break results`() {
        val result = kueryClient.sql { +"SELECT * FROM users" }
            .fetchSize(3)
            .listMap()
        assertThat(result).hasSize(10)
    }

    @Test
    fun `maxRows limits result size`() {
        val result = kueryClient.sql { +"SELECT * FROM users" }
            .maxRows(5)
            .listMap()
        assertThat(result).hasSize(5)
    }

    @Test
    fun `queryTimeoutSeconds does not break normal query`() {
        val result = kueryClient.sql { +"SELECT * FROM users" }
            .queryTimeoutSeconds(10)
            .listMap()
        assertThat(result).hasSize(10)
    }

    @Test
    fun `chained fetchSize, maxRows, and queryTimeoutSeconds limit results to maxRows`() {
        val result = kueryClient.sql { +"SELECT * FROM users" }
            .fetchSize(3)
            .maxRows(4)
            .queryTimeoutSeconds(10)
            .listMap()
        assertThat(result).hasSize(4)
    }

    @Test
    fun `fetchSize does not break sequence results`() {
        val result = kueryClient.sql { +"SELECT * FROM users" }
            .fetchSize(3)
            .sequenceMap()
            .toList()
        assertThat(result).hasSize(10)
    }

    @Test
    fun `maxRows limits sequence result size`() {
        val result = kueryClient.sql { +"SELECT * FROM users" }
            .maxRows(5)
            .sequenceMap()
            .toList()
        assertThat(result).hasSize(5)
    }

    @Test
    fun `queryTimeoutSeconds does not break sequence`() {
        val result = kueryClient.sql { +"SELECT * FROM users" }
            .queryTimeoutSeconds(10)
            .sequenceMap()
            .toList()
        assertThat(result).hasSize(10)
    }

    @Test
    fun `chained fetchSize, maxRows, and queryTimeoutSeconds limit sequence results to maxRows`() {
        val result = kueryClient.sql { +"SELECT * FROM users" }
            .fetchSize(3)
            .maxRows(4)
            .queryTimeoutSeconds(10)
            .sequenceMap()
            .toList()
        assertThat(result).hasSize(4)
    }

    @Test
    fun `options are applied immutably`() {
        // given
        val base = kueryClient.sql { +"SELECT * FROM users" }
        val limited = base.maxRows(3)

        // when
        val baseResult = base.listMap()
        val limitedResult = limited.listMap()

        // then
        assertThat(baseResult).hasSize(10)
        assertThat(limitedResult).hasSize(3)
    }

    companion object {
        private val h2 = H2TestDatabase()
    }
}
