package dev.hsbrysk.kuery.spring.testing.contract.observation

import assertk.assertFailure
import assertk.assertions.isInstanceOf
import com.example.spring.testing.UserRepository
import dev.hsbrysk.kuery.core.KueryClient
import dev.hsbrysk.kuery.spring.testing.ContractDatabase
import io.micrometer.observation.tck.TestObservationRegistry
import io.micrometer.observation.tck.TestObservationRegistryAssert
import kotlinx.coroutines.test.runTest
import org.junit.jupiter.api.AfterEach
import org.junit.jupiter.api.BeforeEach
import org.junit.jupiter.api.Test
import org.springframework.dao.DataAccessException
import org.springframework.dao.EmptyResultDataAccessException

/**
 * Contract shared by the jdbc and r2dbc modules. Each module runs it via a concrete subclass
 * that supplies its `ContractDatabase`.
 *
 * Streaming operations not recording an observation (`sequence` on jdbc, `flow` on r2dbc) and
 * lifecycle semantics (scope ordering, cancellation) are module-specific and live on the
 * concrete subclasses.
 */
@Suppress("TooManyFunctions")
abstract class ObservationContract {
    protected abstract val database: ContractDatabase

    protected val registry: TestObservationRegistry = TestObservationRegistry.create()

    // lazy: `database` is not resolvable yet while this base class initializes.
    protected val kueryClient: KueryClient by lazy { database.kueryClient(observationRegistry = registry) }

    private val userRepository by lazy { UserRepository(kueryClient) }

    @BeforeEach
    fun setUpUsersTable() {
        database.execute(
            """
            CREATE TABLE users (
                user_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                username VARCHAR(50) NOT NULL,
                email VARCHAR(100) NOT NULL
            )
            """.trimIndent(),
        )
        database.execute(
            """
            INSERT INTO users (username, email) VALUES
            ('user1', 'user1@example.com'),
            ('user2', 'user2@example.com')
            """.trimIndent(),
        )
    }

    @AfterEach
    fun dropUsersTable() {
        database.execute("DROP TABLE users")
    }

    @Test
    fun `singleMap records an observation with sqlId and sql`() = runTest {
        userRepository.singleMap(1)
        assertObservation(
            sqlId = "com.example.spring.testing.UserRepository.singleMap",
            sql = "SELECT * FROM users WHERE user_id = :p0",
        )
    }

    @Test
    fun `singleMapOrNull records an observation with sqlId and sql`() = runTest {
        userRepository.singleMapOrNull(1)
        assertObservation(
            sqlId = "com.example.spring.testing.UserRepository.singleMapOrNull",
            sql = "SELECT * FROM users WHERE user_id = :p0",
        )
    }

    @Test
    fun `single records an observation with sqlId and sql`() = runTest {
        userRepository.single(1)
        assertObservation(
            sqlId = "com.example.spring.testing.UserRepository.single",
            sql = "SELECT * FROM users WHERE user_id = :p0",
        )
    }

    @Test
    fun `singleOrNull records an observation with sqlId and sql`() = runTest {
        userRepository.singleOrNull(1)
        assertObservation(
            sqlId = "com.example.spring.testing.UserRepository.singleOrNull",
            sql = "SELECT * FROM users WHERE user_id = :p0",
        )
    }

    @Test
    fun `listMap records an observation with sqlId and sql`() = runTest {
        userRepository.listMap()
        assertObservation(
            sqlId = "com.example.spring.testing.UserRepository.listMap",
            sql = "SELECT * FROM users",
        )
    }

    @Test
    fun `list records an observation with sqlId and sql`() = runTest {
        userRepository.list()
        assertObservation(
            sqlId = "com.example.spring.testing.UserRepository.list",
            sql = "SELECT * FROM users",
        )
    }

    @Test
    fun `rowsUpdated records an observation with sqlId and sql`() = runTest {
        userRepository.rowUpdated("user3", "user3@example.com")
        assertObservation(
            sqlId = "com.example.spring.testing.UserRepository.rowUpdated",
            sql = "INSERT INTO users (username, email) VALUES (:p0, :p1)",
        )
    }

    @Test
    fun `generatedValues records an observation with sqlId and sql`() = runTest {
        userRepository.generatedValues("user3", "user3@example.com")
        assertObservation(
            sqlId = "com.example.spring.testing.UserRepository.generatedValues",
            sql = "INSERT INTO users (username, email) VALUES (:p0, :p1)",
        )
    }

    @Test
    fun `explicit sqlId overload propagates to the observation`() = runTest {
        kueryClient.sql("my.explicit.sql.id") { +"SELECT * FROM users" }.listMap()
        assertObservation(
            sqlId = "my.explicit.sql.id",
            sql = "SELECT * FROM users",
        )
    }

    @Test
    fun `records error when single result is missing`() = runTest {
        assertFailure { userRepository.singleMap(999) }.isInstanceOf(EmptyResultDataAccessException::class)
        TestObservationRegistryAssert.assertThat(registry)
            .doesNotHaveAnyRemainingCurrentObservation()
            .hasObservationWithNameEqualTo("kuery.client.fetches")
            .that()
            .hasBeenStarted()
            .hasBeenStopped()
            .hasError()
    }

    @Test
    fun `records error when the sql execution fails`() = runTest {
        assertFailure {
            kueryClient.sql { +"SELECT * FROM missing_table" }.listMap()
        }.isInstanceOf(DataAccessException::class)
        TestObservationRegistryAssert.assertThat(registry)
            .doesNotHaveAnyRemainingCurrentObservation()
            .hasObservationWithNameEqualTo("kuery.client.fetches")
            .that()
            .hasBeenStarted()
            .hasBeenStopped()
            .hasError()
    }

    protected fun assertObservation(
        sqlId: String,
        sql: String,
    ) {
        TestObservationRegistryAssert.assertThat(registry)
            .doesNotHaveAnyRemainingCurrentObservation()
            .hasObservationWithNameEqualTo("kuery.client.fetches")
            .that()
            .hasLowCardinalityKeyValue("sql.id", sqlId)
            .hasHighCardinalityKeyValue("sql", sql)
            .hasBeenStarted()
            .hasBeenStopped()
    }
}
