package dev.hsbrysk.kuery.spring.testing

import dev.hsbrysk.kuery.core.KueryClient
import io.micrometer.observation.ObservationRegistry

/**
 * A database an implementation module plugs into a contract test.
 *
 * The jdbc implementation returns its [dev.hsbrysk.kuery.core.KueryBlockingClient] wrapped in
 * [BlockingKueryClientAdapter], so contracts are written once against [KueryClient].
 */
interface ContractDatabase {
    fun kueryClient(
        converters: List<Any> = emptyList(),
        observationRegistry: ObservationRegistry? = null,
    ): KueryClient

    /**
     * Executes DDL / seed SQL directly through the underlying Spring client, bypassing Kuery
     * Client. Deliberately non-suspending so contract `@BeforeEach` / `@AfterEach` methods stay
     * plain methods.
     */
    fun execute(sql: String)

    fun setUpForConverterTest() {
        execute(
            """
            CREATE TABLE converter
            (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                text VARCHAR(255) DEFAULT NULL
            )
            """.trimIndent(),
        )
    }

    fun tearDownForConverterTest() {
        execute("DROP TABLE converter")
    }
}
