package dev.hsbrysk.kuery.spring.r2dbc

import assertk.assertFailure
import assertk.assertions.isInstanceOf
import com.example.spring.r2dbc.UserRepository
import io.micrometer.observation.tck.TestObservationRegistry
import io.micrometer.observation.tck.TestObservationRegistryAssert
import kotlinx.coroutines.test.runTest
import org.junit.jupiter.api.AfterEach
import org.junit.jupiter.api.BeforeEach
import org.junit.jupiter.api.Test
import org.springframework.dao.EmptyResultDataAccessException
import org.springframework.r2dbc.core.awaitRowsUpdated

class ObservationTest {
    private val registry = TestObservationRegistry.create()
    private val kueryClient = h2.kueryClient(observationRegistry = registry)
    private val userRepository = UserRepository(kueryClient)

    @BeforeEach
    fun setUp() = runTest {
        h2.databaseClient.sql(
            """
            CREATE TABLE users (
                user_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                username VARCHAR(50) NOT NULL,
                email VARCHAR(100) NOT NULL
            )
            """.trimIndent(),
        ).fetch().awaitRowsUpdated()
        h2.databaseClient.sql(
            """
            INSERT INTO users (username, email) VALUES
            ('user1', 'user1@example.com'),
            ('user2', 'user2@example.com')
            """.trimIndent(),
        ).fetch().awaitRowsUpdated()
    }

    @AfterEach
    fun testDown() = runTest {
        h2.databaseClient.sql("DROP TABLE users").fetch().awaitRowsUpdated()
    }

    @Test
    fun singleMap() = runTest {
        userRepository.singleMap(1)
        assertObservation(
            sqlId = "com.example.spring.r2dbc.UserRepository.singleMap",
            sql = "SELECT * FROM users WHERE user_id = :p0",
        )
    }

    @Test
    fun singleMapOrNull() = runTest {
        userRepository.singleMapOrNull(1)
        assertObservation(
            sqlId = "com.example.spring.r2dbc.UserRepository.singleMapOrNull",
            sql = "SELECT * FROM users WHERE user_id = :p0",
        )
    }

    @Test
    fun single() = runTest {
        userRepository.single(1)
        assertObservation(
            sqlId = "com.example.spring.r2dbc.UserRepository.single",
            sql = "SELECT * FROM users WHERE user_id = :p0",
        )
    }

    @Test
    fun singleOrNull() = runTest {
        userRepository.singleOrNull(1)
        assertObservation(
            sqlId = "com.example.spring.r2dbc.UserRepository.singleOrNull",
            sql = "SELECT * FROM users WHERE user_id = :p0",
        )
    }

    @Test
    fun listMap() = runTest {
        userRepository.listMap()
        assertObservation(
            sqlId = "com.example.spring.r2dbc.UserRepository.listMap",
            sql = "SELECT * FROM users",
        )
    }

    @Test
    fun list() = runTest {
        userRepository.list()
        assertObservation(
            sqlId = "com.example.spring.r2dbc.UserRepository.list",
            sql = "SELECT * FROM users",
        )
    }

    @Test
    fun rowUpdated() = runTest {
        userRepository.rowUpdated("user3", "user3@example.com")
        assertObservation(
            sqlId = "com.example.spring.r2dbc.UserRepository.rowUpdated",
            sql = "INSERT INTO users (username, email) VALUES (:p0, :p1)",
        )
    }

    @Test
    fun generatedValues() = runTest {
        userRepository.generatedValues("user3", "user3@example.com")
        assertObservation(
            sqlId = "com.example.spring.r2dbc.UserRepository.generatedValues",
            sql = "INSERT INTO users (username, email) VALUES (:p0, :p1)",
        )
    }

    @Test
    fun `records error when single result is missing`() = runTest {
        assertFailure { userRepository.singleMap(999) }.isInstanceOf(EmptyResultDataAccessException::class)
        TestObservationRegistryAssert.assertThat(registry)
            .doesNotHaveAnyRemainingCurrentObservation()
            .hasObservationWithNameEqualTo("kuery.client.fetches")
            .that()
            .hasBeenStarted()
            .hasBeenStopped()
            .hasError()
    }

    private fun assertObservation(
        sqlId: String,
        sql: String,
    ) {
        TestObservationRegistryAssert.assertThat(registry)
            .doesNotHaveAnyRemainingCurrentObservation()
            .hasObservationWithNameEqualTo("kuery.client.fetches")
            .that()
            .hasLowCardinalityKeyValue("sql.id", sqlId)
            .hasHighCardinalityKeyValue("sql", sql)
            .hasBeenStarted()
            .hasBeenStopped()
    }

    companion object {
        private val h2 = H2TestDatabase()
    }
}
