package dev.hsbrysk.kuery.spring.r2dbc

import assertk.assertFailure
import assertk.assertions.isInstanceOf
import com.example.spring.r2dbc.UserRepository
import io.micrometer.observation.tck.TestObservationRegistry
import io.micrometer.observation.tck.TestObservationRegistryAssert
import io.r2dbc.spi.Connection
import io.r2dbc.spi.ConnectionFactory
import io.r2dbc.spi.Result
import io.r2dbc.spi.Statement
import kotlinx.coroutines.CoroutineStart
import kotlinx.coroutines.cancelAndJoin
import kotlinx.coroutines.launch
import kotlinx.coroutines.test.runTest
import org.junit.jupiter.api.AfterEach
import org.junit.jupiter.api.BeforeEach
import org.junit.jupiter.api.Test
import org.reactivestreams.Publisher
import org.springframework.dao.DataAccessException
import org.springframework.dao.EmptyResultDataAccessException
import org.springframework.r2dbc.core.awaitRowsUpdated
import reactor.core.publisher.Flux

class ObservationTest {
    private val registry = TestObservationRegistry.create()
    private val kueryClient = h2.kueryClient(observationRegistry = registry)
    private val userRepository = UserRepository(kueryClient)

    @BeforeEach
    fun setUp() = runTest {
        h2.databaseClient.sql(
            """
            CREATE TABLE users (
                user_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                username VARCHAR(50) NOT NULL,
                email VARCHAR(100) NOT NULL
            )
            """.trimIndent(),
        ).fetch().awaitRowsUpdated()
        h2.databaseClient.sql(
            """
            INSERT INTO users (username, email) VALUES
            ('user1', 'user1@example.com'),
            ('user2', 'user2@example.com')
            """.trimIndent(),
        ).fetch().awaitRowsUpdated()
    }

    @AfterEach
    fun tearDown() = runTest {
        h2.databaseClient.sql("DROP TABLE users").fetch().awaitRowsUpdated()
    }

    @Test
    fun `singleMap records an observation with sqlId and sql`() = runTest {
        userRepository.singleMap(1)
        assertObservation(
            sqlId = "com.example.spring.r2dbc.UserRepository.singleMap",
            sql = "SELECT * FROM users WHERE user_id = :p0",
        )
    }

    @Test
    fun `singleMapOrNull records an observation with sqlId and sql`() = runTest {
        userRepository.singleMapOrNull(1)
        assertObservation(
            sqlId = "com.example.spring.r2dbc.UserRepository.singleMapOrNull",
            sql = "SELECT * FROM users WHERE user_id = :p0",
        )
    }

    @Test
    fun `single records an observation with sqlId and sql`() = runTest {
        userRepository.single(1)
        assertObservation(
            sqlId = "com.example.spring.r2dbc.UserRepository.single",
            sql = "SELECT * FROM users WHERE user_id = :p0",
        )
    }

    @Test
    fun `singleOrNull records an observation with sqlId and sql`() = runTest {
        userRepository.singleOrNull(1)
        assertObservation(
            sqlId = "com.example.spring.r2dbc.UserRepository.singleOrNull",
            sql = "SELECT * FROM users WHERE user_id = :p0",
        )
    }

    @Test
    fun `listMap records an observation with sqlId and sql`() = runTest {
        userRepository.listMap()
        assertObservation(
            sqlId = "com.example.spring.r2dbc.UserRepository.listMap",
            sql = "SELECT * FROM users",
        )
    }

    @Test
    fun `list records an observation with sqlId and sql`() = runTest {
        userRepository.list()
        assertObservation(
            sqlId = "com.example.spring.r2dbc.UserRepository.list",
            sql = "SELECT * FROM users",
        )
    }

    @Test
    fun `rowsUpdated records an observation with sqlId and sql`() = runTest {
        userRepository.rowUpdated("user3", "user3@example.com")
        assertObservation(
            sqlId = "com.example.spring.r2dbc.UserRepository.rowUpdated",
            sql = "INSERT INTO users (username, email) VALUES (:p0, :p1)",
        )
    }

    @Test
    fun `generatedValues records an observation with sqlId and sql`() = runTest {
        userRepository.generatedValues("user3", "user3@example.com")
        assertObservation(
            sqlId = "com.example.spring.r2dbc.UserRepository.generatedValues",
            sql = "INSERT INTO users (username, email) VALUES (:p0, :p1)",
        )
    }

    @Test
    fun `explicit sqlId overload propagates to the observation`() = runTest {
        kueryClient.sql("my.explicit.sql.id") { +"SELECT * FROM users" }.listMap()
        assertObservation(
            sqlId = "my.explicit.sql.id",
            sql = "SELECT * FROM users",
        )
    }

    @Test
    fun `records error when single result is missing`() = runTest {
        assertFailure { userRepository.singleMap(999) }.isInstanceOf(EmptyResultDataAccessException::class)
        TestObservationRegistryAssert.assertThat(registry)
            .doesNotHaveAnyRemainingCurrentObservation()
            .hasObservationWithNameEqualTo("kuery.client.fetches")
            .that()
            .hasBeenStarted()
            .hasBeenStopped()
            .hasError()
    }

    @Test
    fun `records error when the sql execution fails`() = runTest {
        assertFailure {
            kueryClient.sql { +"SELECT * FROM missing_table" }.listMap()
        }.isInstanceOf(DataAccessException::class)
        TestObservationRegistryAssert.assertThat(registry)
            .doesNotHaveAnyRemainingCurrentObservation()
            .hasObservationWithNameEqualTo("kuery.client.fetches")
            .that()
            .hasBeenStarted()
            .hasBeenStopped()
            .hasError()
    }

    @Test
    fun `stops the observation without error when the fetch is cancelled`() = runTest {
        // given
        val neverClient = SpringR2dbcKueryClient.builder()
            .connectionFactory(NeverExecutingConnectionFactory(h2.connectionFactory))
            .observationRegistry(registry)
            .build()

        // when
        // UNDISPATCHED runs the coroutine up to its first suspension point, so the fetch is
        // guaranteed to have subscribed (and the observation to have started) before we cancel.
        val job = launch(start = CoroutineStart.UNDISPATCHED) {
            neverClient.sql { +"SELECT * FROM users" }.singleMap()
        }
        job.cancelAndJoin()

        // then
        TestObservationRegistryAssert.assertThat(registry)
            .doesNotHaveAnyRemainingCurrentObservation()
            .hasObservationWithNameEqualTo("kuery.client.fetches")
            .that()
            .hasBeenStarted()
            .hasBeenStopped()
            .doesNotHaveError()
    }

    private fun assertObservation(
        sqlId: String,
        sql: String,
    ) {
        TestObservationRegistryAssert.assertThat(registry)
            .doesNotHaveAnyRemainingCurrentObservation()
            .hasObservationWithNameEqualTo("kuery.client.fetches")
            .that()
            .hasLowCardinalityKeyValue("sql.id", sqlId)
            .hasHighCardinalityKeyValue("sql", sql)
            .hasBeenStarted()
            .hasBeenStopped()
    }

    private class NeverExecutingConnectionFactory(private val delegate: ConnectionFactory) :
        ConnectionFactory by delegate {
        override fun create(): Publisher<out Connection> = Flux.from(delegate.create())
            .map { NeverExecutingConnection(it) }
    }

    private class NeverExecutingConnection(private val delegate: Connection) : Connection by delegate {
        override fun createStatement(sql: String): Statement = NeverExecutingStatement(delegate.createStatement(sql))
    }

    // Fluent methods must return `this` (not the delegate) so that execute() below stays wrapped.
    private class NeverExecutingStatement(private val delegate: Statement) : Statement {
        override fun add(): Statement = apply { delegate.add() }

        override fun bind(
            index: Int,
            value: Any,
        ): Statement = apply { delegate.bind(index, value) }

        override fun bind(
            name: String,
            value: Any,
        ): Statement = apply { delegate.bind(name, value) }

        override fun bindNull(
            index: Int,
            type: Class<*>,
        ): Statement = apply { delegate.bindNull(index, type) }

        override fun bindNull(
            name: String,
            type: Class<*>,
        ): Statement = apply { delegate.bindNull(name, type) }

        override fun fetchSize(rows: Int): Statement = apply { delegate.fetchSize(rows) }

        override fun returnGeneratedValues(vararg columns: String): Statement =
            apply { delegate.returnGeneratedValues(*columns) }

        override fun execute(): Publisher<out Result> = Flux.never()
    }

    companion object {
        private val h2 = H2TestDatabase()
    }
}
