package dev.hsbrysk.kuery.spring.r2dbc

import assertk.assertThat
import assertk.assertions.containsExactly
import com.example.spring.r2dbc.UserRepository
import io.r2dbc.spi.Connection
import io.r2dbc.spi.ConnectionFactory
import io.r2dbc.spi.Result
import io.r2dbc.spi.Statement
import kotlinx.coroutines.flow.collect
import kotlinx.coroutines.test.runTest
import org.junit.jupiter.api.AfterEach
import org.junit.jupiter.api.BeforeEach
import org.junit.jupiter.api.Test
import org.reactivestreams.Publisher
import org.springframework.r2dbc.core.awaitRowsUpdated
import reactor.core.publisher.Flux
import java.util.concurrent.CopyOnWriteArrayList

class SqlIdReactorContextTest {
    private val capturedSqlIds = CopyOnWriteArrayList<String?>()
    private val kueryClient = SpringR2dbcKueryClient.builder()
        .connectionFactory(SqlIdCapturingConnectionFactory(h2.connectionFactory, capturedSqlIds))
        .enableAutoSqlIdGeneration(true)
        .build()
    private val userRepository = UserRepository(kueryClient)

    @BeforeEach
    fun setUp() = runTest {
        h2.databaseClient.sql(
            """
            CREATE TABLE users (
                user_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                username VARCHAR(50) NOT NULL,
                email VARCHAR(100) NOT NULL
            )
            """.trimIndent(),
        ).fetch().awaitRowsUpdated()
        h2.databaseClient.sql(
            """
            INSERT INTO users (username, email) VALUES
            ('user1', 'user1@example.com'),
            ('user2', 'user2@example.com')
            """.trimIndent(),
        ).fetch().awaitRowsUpdated()
        capturedSqlIds.clear()
    }

    @AfterEach
    fun tearDown() = runTest {
        h2.databaseClient.sql("DROP TABLE users").fetch().awaitRowsUpdated()
    }

    @Test
    fun `singleMap propagates the auto-generated sqlId to statement execution`() = runTest {
        userRepository.singleMap(1)
        assertThat(capturedSqlIds).containsExactly("com.example.spring.r2dbc.UserRepository.singleMap")
    }

    @Test
    fun `singleMapOrNull propagates the auto-generated sqlId to statement execution`() = runTest {
        userRepository.singleMapOrNull(1)
        assertThat(capturedSqlIds).containsExactly("com.example.spring.r2dbc.UserRepository.singleMapOrNull")
    }

    @Test
    fun `single propagates the auto-generated sqlId to statement execution`() = runTest {
        userRepository.single(1)
        assertThat(capturedSqlIds).containsExactly("com.example.spring.r2dbc.UserRepository.single")
    }

    @Test
    fun `singleOrNull propagates the auto-generated sqlId to statement execution`() = runTest {
        userRepository.singleOrNull(1)
        assertThat(capturedSqlIds).containsExactly("com.example.spring.r2dbc.UserRepository.singleOrNull")
    }

    @Test
    fun `listMap propagates the auto-generated sqlId to statement execution`() = runTest {
        userRepository.listMap()
        assertThat(capturedSqlIds).containsExactly("com.example.spring.r2dbc.UserRepository.listMap")
    }

    @Test
    fun `list propagates the auto-generated sqlId to statement execution`() = runTest {
        userRepository.list()
        assertThat(capturedSqlIds).containsExactly("com.example.spring.r2dbc.UserRepository.list")
    }

    @Test
    fun `flowMap propagates the auto-generated sqlId to statement execution`() = runTest {
        userRepository.flowMap().collect()
        assertThat(capturedSqlIds).containsExactly("com.example.spring.r2dbc.UserRepository.flowMap")
    }

    @Test
    fun `flow propagates the auto-generated sqlId to statement execution`() = runTest {
        userRepository.flow().collect()
        assertThat(capturedSqlIds).containsExactly("com.example.spring.r2dbc.UserRepository.flow")
    }

    @Test
    fun `rowsUpdated propagates the auto-generated sqlId to statement execution`() = runTest {
        userRepository.rowUpdated("user3", "user3@example.com")
        assertThat(capturedSqlIds).containsExactly("com.example.spring.r2dbc.UserRepository.rowUpdated")
    }

    @Test
    fun `generatedValues propagates the auto-generated sqlId to statement execution`() = runTest {
        userRepository.generatedValues("user3", "user3@example.com")
        assertThat(capturedSqlIds).containsExactly("com.example.spring.r2dbc.UserRepository.generatedValues")
    }

    private class SqlIdCapturingConnectionFactory(
        private val delegate: ConnectionFactory,
        private val captured: MutableList<String?>,
    ) : ConnectionFactory by delegate {
        override fun create(): Publisher<out Connection> = Flux.from(delegate.create())
            .map { SqlIdCapturingConnection(it, captured) }
    }

    private class SqlIdCapturingConnection(
        private val delegate: Connection,
        private val captured: MutableList<String?>,
    ) : Connection by delegate {
        override fun createStatement(sql: String): Statement =
            SqlIdCapturingStatement(delegate.createStatement(sql), captured)
    }

    // Fluent methods must return `this` (not the delegate) so that execute() below stays wrapped.
    private class SqlIdCapturingStatement(
        private val delegate: Statement,
        private val captured: MutableList<String?>,
    ) : Statement {
        override fun add(): Statement = apply { delegate.add() }

        override fun bind(
            index: Int,
            value: Any,
        ): Statement = apply { delegate.bind(index, value) }

        override fun bind(
            name: String,
            value: Any,
        ): Statement = apply { delegate.bind(name, value) }

        override fun bindNull(
            index: Int,
            type: Class<*>,
        ): Statement = apply { delegate.bindNull(index, type) }

        override fun bindNull(
            name: String,
            type: Class<*>,
        ): Statement = apply { delegate.bindNull(name, type) }

        override fun fetchSize(rows: Int): Statement = apply { delegate.fetchSize(rows) }

        override fun returnGeneratedValues(vararg columns: String): Statement =
            apply { delegate.returnGeneratedValues(*columns) }

        override fun execute(): Publisher<out Result> = Flux.deferContextual { context ->
            captured.add(SpringR2dbcKueryClient.sqlId(context))
            Flux.from(delegate.execute())
        }
    }

    companion object {
        private val h2 = H2TestDatabase()
    }
}
