package dev.hsbrysk.kuery.spring.r2dbc

import assertk.assertThat
import assertk.assertions.hasSize
import kotlinx.coroutines.test.runTest
import org.junit.jupiter.api.AfterEach
import org.junit.jupiter.api.BeforeEach
import org.junit.jupiter.api.Test
import org.springframework.r2dbc.core.awaitRowsUpdated

class StatementOptionsTest {
    private val kueryClient = h2.kueryClient()

    @BeforeEach
    fun setUp() = runTest {
        h2.databaseClient.sql(
            """
            CREATE TABLE users (
                user_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                username VARCHAR(50) NOT NULL,
                email VARCHAR(100) NOT NULL
            )
            """.trimIndent(),
        ).fetch().awaitRowsUpdated()
        repeat(10) { i ->
            h2.databaseClient.sql("INSERT INTO users (username, email) VALUES ('user$i', 'user$i@example.com')")
                .fetch().awaitRowsUpdated()
        }
    }

    @AfterEach
    fun tearDown() = runTest {
        h2.databaseClient.sql("DROP TABLE users").fetch().awaitRowsUpdated()
    }

    @Test
    fun `fetchSize does not break results`() = runTest {
        val result = kueryClient.sql { +"SELECT * FROM users" }
            .fetchSize(3)
            .listMap()
        assertThat(result).hasSize(10)
    }

    @Test
    fun `options are applied immutably`() = runTest {
        // given
        val base = kueryClient.sql { +"SELECT * FROM users" }
        val withFetchSize = base.fetchSize(3)

        // when
        val baseResult = base.listMap()
        val withFetchSizeResult = withFetchSize.listMap()

        // then
        assertThat(baseResult).hasSize(10)
        assertThat(withFetchSizeResult).hasSize(10)
    }

    companion object {
        private val h2 = H2TestDatabase()
    }
}
