package dev.hsbrysk.kuery.spring.testing.contract.sqlid

import assertk.assertThat
import assertk.assertions.containsExactly
import com.example.spring.testing.UserRepository
import dev.hsbrysk.kuery.core.KueryClient
import dev.hsbrysk.kuery.spring.testing.ContractDatabase
import io.micrometer.observation.ObservationRegistry
import io.micrometer.observation.tck.TestObservationRegistry
import kotlinx.coroutines.test.runTest
import org.junit.jupiter.api.AfterEach
import org.junit.jupiter.api.BeforeEach
import org.junit.jupiter.api.Test

/**
 * Pins the builder's default rule for auto sqlId generation: it follows whether an
 * observationRegistry is set, and an explicit enableAutoSqlIdGeneration always wins.
 *
 * Contract shared by the jdbc and r2dbc modules. The capture mechanism is inherently one-sided
 * (ThreadLocal on jdbc, Reactor context on r2dbc), so each concrete subclass supplies a client
 * whose driver-level hooks record the propagated sqlId into [capturedSqlIds]. How the sqlId
 * propagates is not asserted here — that stays in each module's own tests.
 */
abstract class SqlIdGenerationDefaultContract {
    protected abstract val database: ContractDatabase

    protected abstract val capturedSqlIds: MutableList<String?>

    protected abstract fun capturingKueryClient(
        observationRegistry: ObservationRegistry? = null,
        enableAutoSqlIdGeneration: Boolean? = null,
    ): KueryClient

    @BeforeEach
    fun setUpUsersTable() {
        database.execute(
            """
            CREATE TABLE users (
                user_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                username VARCHAR(50) NOT NULL,
                email VARCHAR(100) NOT NULL
            )
            """.trimIndent(),
        )
        database.execute("INSERT INTO users (username, email) VALUES ('user1', 'user1@example.com')")
        capturedSqlIds.clear()
    }

    @AfterEach
    fun dropUsersTable() {
        database.execute("DROP TABLE users")
    }

    @Test
    fun `auto sqlId generation defaults to enabled when an observationRegistry is set`() = runTest {
        val kueryClient = capturingKueryClient(observationRegistry = TestObservationRegistry.create())

        UserRepository(kueryClient).singleMap(1)

        assertThat(capturedSqlIds).containsExactly("com.example.spring.testing.UserRepository.singleMap")
    }

    @Test
    fun `auto sqlId generation defaults to disabled without an observationRegistry`() = runTest {
        val kueryClient = capturingKueryClient()

        UserRepository(kueryClient).singleMap(1)

        assertThat(capturedSqlIds).containsExactly("NONE")
    }

    @Test
    fun `explicit false disables auto sqlId generation even with an observationRegistry`() = runTest {
        val kueryClient = capturingKueryClient(
            observationRegistry = TestObservationRegistry.create(),
            enableAutoSqlIdGeneration = false,
        )

        UserRepository(kueryClient).singleMap(1)

        assertThat(capturedSqlIds).containsExactly("NONE")
    }

    @Test
    fun `explicit true enables auto sqlId generation without an observationRegistry`() = runTest {
        val kueryClient = capturingKueryClient(enableAutoSqlIdGeneration = true)

        UserRepository(kueryClient).singleMap(1)

        assertThat(capturedSqlIds).containsExactly("com.example.spring.testing.UserRepository.singleMap")
    }
}
