package dev.hsbrysk.kuery.spring.testing.contract.usage

import assertk.assertFailure
import assertk.assertThat
import assertk.assertions.isEmpty
import assertk.assertions.isEqualTo
import assertk.assertions.isInstanceOf
import assertk.assertions.isNull
import dev.hsbrysk.kuery.core.DelicateKueryClientApi
import dev.hsbrysk.kuery.core.KueryClient
import dev.hsbrysk.kuery.core.SqlBuilder
import dev.hsbrysk.kuery.core.list
import dev.hsbrysk.kuery.core.single
import dev.hsbrysk.kuery.core.singleOrNull
import dev.hsbrysk.kuery.spring.testing.ContractDatabase
import dev.hsbrysk.kuery.spring.testing.ExceptionProfile
import kotlinx.coroutines.test.runTest
import org.junit.jupiter.api.AfterEach
import org.junit.jupiter.api.BeforeEach
import org.junit.jupiter.api.Test
import org.springframework.dao.EmptyResultDataAccessException
import org.springframework.dao.IncorrectResultSizeDataAccessException
import java.math.BigDecimal
import java.time.LocalDate

/**
 * Contract shared by the jdbc and r2dbc modules. Each module runs it via a concrete subclass
 * that supplies its `ContractDatabase`.
 */
@Suppress("TooManyFunctions")
abstract class BasicUsageContract {
    protected abstract val database: ContractDatabase

    protected abstract val exceptionProfile: ExceptionProfile

    // lazy: `database` is not resolvable yet while this base class initializes.
    protected val kueryClient: KueryClient by lazy { database.kueryClient() }

    @Suppress("LongMethod")
    @BeforeEach
    fun setUpUsageTables() {
        val queries = listOf(
            """
            CREATE TABLE users (
                user_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                username VARCHAR(50) NOT NULL,
                email VARCHAR(100) NOT NULL
            )
            """.trimIndent(),
            """
            CREATE TABLE orders (
                order_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                user_id INT,
                order_date DATE,
                amount DECIMAL(10, 2),
                FOREIGN KEY (user_id) REFERENCES users(user_id)
            )
            """.trimIndent(),
            """
            CREATE TABLE products (
                product_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                product_name VARCHAR(100),
                price DECIMAL(10, 2)
            )
            """.trimIndent(),
            """
            CREATE TABLE order_items (
                order_item_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                order_id INT,
                product_id INT,
                quantity INT,
                FOREIGN KEY (order_id) REFERENCES orders(order_id),
                FOREIGN KEY (product_id) REFERENCES products(product_id)
            )
            """.trimIndent(),
            """
            INSERT INTO users (username, email) VALUES
            ('user1', 'user1@example.com'),
            ('user2', 'user2@example.com')
            """.trimIndent(),
            """
            INSERT INTO orders (user_id, order_date, amount) VALUES
            (1, '2023-06-01', 100.00),
            (2, '2023-06-02', 150.00)
            """.trimIndent(),
            """
            INSERT INTO products (product_name, price) VALUES
            ('Product A', 25.00),
            ('Product B', 50.00)
            """.trimIndent(),
            """
            INSERT INTO order_items (order_id, product_id, quantity) VALUES
            (1, 1, 2),
            (1, 2, 1),
            (2, 1, 1)
            """.trimIndent(),
        )
        queries.forEach {
            database.execute(it)
        }
    }

    @AfterEach
    fun dropUsageTables() {
        val queries = listOf(
            "DROP TABLE IF EXISTS order_items",
            "DROP TABLE IF EXISTS orders",
            "DROP TABLE IF EXISTS products",
            "DROP TABLE IF EXISTS users",
        )
        queries.forEach {
            database.execute(it)
        }
    }

    data class User(
        val userId: Int,
        val username: String,
        val email: String,
    )

    @Test
    fun `singleMap returns the only row as a map`() = runTest {
        val userId = 1
        val result = kueryClient.sql { +"SELECT * FROM users WHERE user_id = $userId" }.singleMap()
        assertThat(result).isEqualTo(
            mapOf(
                "user_id" to 1,
                "username" to "user1",
                "email" to "user1@example.com",
            ),
        )
    }

    @Test
    fun `singleMap throws when no rows match`() = runTest {
        val userId = 5
        assertFailure {
            kueryClient.sql { +"SELECT * FROM users WHERE user_id = $userId" }.singleMap()
        }.isInstanceOf(EmptyResultDataAccessException::class)
    }

    @Test
    fun `singleMap throws when more than one row matches`() = runTest {
        assertFailure {
            kueryClient.sql { +"SELECT * FROM users" }.singleMap()
        }.isInstanceOf(IncorrectResultSizeDataAccessException::class)
    }

    @Test
    fun `singleMapOrNull returns the only row as a map`() = runTest {
        val userId = 1
        val result = kueryClient.sql { +"SELECT * FROM users WHERE user_id = $userId" }.singleMapOrNull()
        assertThat(result).isEqualTo(
            mapOf(
                "user_id" to 1,
                "username" to "user1",
                "email" to "user1@example.com",
            ),
        )
    }

    @Test
    fun `singleMapOrNull returns null when no rows match`() = runTest {
        val userId = 5
        val result = kueryClient.sql { +"SELECT * FROM users WHERE user_id = $userId" }.singleMapOrNull()
        assertThat(result).isNull()
    }

    @Test
    fun `singleMapOrNull throws when more than one row matches`() = runTest {
        assertFailure {
            kueryClient.sql { +"SELECT * FROM users" }.singleMapOrNull()
        }.isInstanceOf(IncorrectResultSizeDataAccessException::class)
    }

    @Test
    fun `single returns the only row mapped to a data class`() = runTest {
        val userId = 1
        val result: User = kueryClient.sql { +"SELECT * FROM users WHERE user_id = $userId" }.single()
        assertThat(result).isEqualTo(
            User(
                userId = 1,
                username = "user1",
                email = "user1@example.com",
            ),
        )
    }

    @Test
    fun `single throws when the target class does not match the selected columns`() = runTest {
        data class InvalidUser(
            val userId: Int,
            val invalid: String,
        )

        // The concrete exception type is module-specific; each module's ExceptionProfile
        // documents why.
        val userId = 1
        assertFailure {
            kueryClient.sql { +"SELECT * FROM users WHERE user_id = $userId" }.single<InvalidUser>()
        }.isInstanceOf(exceptionProfile.columnMismatchException)
    }

    @Test
    fun `single throws when no rows match`() = runTest {
        val userId = 5
        assertFailure {
            kueryClient.sql { +"SELECT * FROM users WHERE user_id = $userId" }.single<User>()
        }.isInstanceOf(EmptyResultDataAccessException::class)
    }

    @Test
    fun `single throws when more than one row matches`() = runTest {
        assertFailure {
            kueryClient.sql { +"SELECT * FROM users" }.single<User>()
        }.isInstanceOf(IncorrectResultSizeDataAccessException::class)
    }

    @Test
    fun `singleOrNull returns the only row mapped to a data class`() = runTest {
        val userId = 1
        val result: User? = kueryClient.sql { +"SELECT * FROM users WHERE user_id = $userId" }.singleOrNull()
        assertThat(result).isEqualTo(
            User(
                userId = 1,
                username = "user1",
                email = "user1@example.com",
            ),
        )
    }

    @Test
    fun `singleOrNull returns null when no rows match`() = runTest {
        val userId = 5
        val result: User? = kueryClient.sql { +"SELECT * FROM users WHERE user_id = $userId" }.singleOrNull()
        assertThat(result).isNull()
    }

    @Test
    fun `singleOrNull throws when more than one row matches`() = runTest {
        assertFailure {
            kueryClient.sql { +"SELECT * FROM users" }.singleOrNull<User>()
        }.isInstanceOf(IncorrectResultSizeDataAccessException::class)
    }

    @Test
    fun `listMap returns all rows as maps`() = runTest {
        val result = kueryClient.sql { +"SELECT * FROM users ORDER BY user_id" }.listMap()
        assertThat(result).isEqualTo(
            listOf(
                mapOf(
                    "user_id" to 1,
                    "username" to "user1",
                    "email" to "user1@example.com",
                ),
                mapOf(
                    "user_id" to 2,
                    "username" to "user2",
                    "email" to "user2@example.com",
                ),
            ),
        )
    }

    @Test
    fun `listMap returns an empty list when no rows match`() = runTest {
        val userId = 3
        val result = kueryClient.sql { +"SELECT * FROM users WHERE user_id > $userId" }.listMap()
        assertThat(result).isEmpty()
    }

    @Test
    fun `list returns all rows mapped to data classes`() = runTest {
        val result: List<User> = kueryClient.sql { +"SELECT * FROM users ORDER BY user_id" }.list()
        assertThat(result).isEqualTo(
            listOf(
                User(
                    userId = 1,
                    username = "user1",
                    email = "user1@example.com",
                ),
                User(
                    userId = 2,
                    username = "user2",
                    email = "user2@example.com",
                ),
            ),
        )
    }

    @Test
    fun `list returns an empty list when no rows match`() = runTest {
        val userId = 3
        val result: List<User> = kueryClient.sql { +"SELECT * FROM users WHERE user_id > $userId" }.list()
        assertThat(result).isEmpty()
    }

    @Test
    fun `rowsUpdated returns the number of inserted rows`() = runTest {
        val username = "user3"
        val email = "user3"
        val result = kueryClient
            .sql {
                +"INSERT INTO users (username, email) VALUES ($username, $email)"
            }
            .rowsUpdated()
        assertThat(result).isEqualTo(1)
    }

    @Test
    fun `rowsUpdated returns zero when no rows are affected`() = runTest {
        val userId = 5
        val result = kueryClient
            .sql {
                +"DELETE FROM users WHERE user_id = $userId"
            }
            .rowsUpdated()
        assertThat(result).isEqualTo(0)
    }

    @Test
    fun `rowsUpdated returns the count across all updated rows`() = runTest {
        val result = kueryClient
            .sql {
                +"UPDATE users SET username = 'updated'"
            }
            .rowsUpdated()
        assertThat(result).isEqualTo(2)
    }

    @Test
    fun `generatedValues returns the auto-generated key of the inserted row`() = runTest {
        val username = "user3"
        val email = "user3"
        val result = kueryClient
            .sql {
                +"INSERT INTO users (username, email) VALUES ($username, $email)"
            }
            .generatedValues("user_id")
        assertThat(result).isEqualTo(mapOf("user_id" to 3))
    }

    @Test
    fun `two-table join maps combined columns to a data class`() = runTest {
        data class UserOrder(
            val username: String,
            val orderId: Int,
            val orderDate: LocalDate,
            val amount: BigDecimal,
        )

        val userId = 1
        val result: List<UserOrder> = kueryClient
            .sql {
                +"""
                SELECT users.username, orders.order_id, orders.order_date, orders.amount
                FROM users
                JOIN orders ON users.user_id = orders.user_id
                WHERE
                    users.user_id = $userId
                """.trimIndent()
            }
            .list()
        assertThat(result).isEqualTo(
            listOf(
                UserOrder(
                    username = "user1",
                    orderId = 1,
                    orderDate = LocalDate.of(2023, 6, 1),
                    amount = BigDecimal("100.00"),
                ),
            ),
        )
    }

    @Test
    fun `three-table join maps combined columns to data classes`() = runTest {
        data class OrderProduct(
            val orderId: Int,
            val productName: String,
            val quantity: Int,
        )

        val result: List<OrderProduct> = kueryClient
            .sql {
                +"""
                SELECT orders.order_id, products.product_name, order_items.quantity
                FROM orders
                JOIN order_items ON orders.order_id = order_items.order_id
                JOIN products ON order_items.product_id = products.product_id
                ORDER BY orders.order_id, order_items.order_item_id
                """.trimIndent()
            }
            .list()
        assertThat(result).isEqualTo(
            listOf(
                OrderProduct(orderId = 1, productName = "Product A", quantity = 2),
                OrderProduct(orderId = 1, productName = "Product B", quantity = 1),
                OrderProduct(orderId = 2, productName = "Product A", quantity = 1),
            ),
        )
    }

    @Test
    fun `sql fragments can be composed via an extension function using addUnsafe and bind`() = runTest {
        @OptIn(DelicateKueryClientApi::class)
        fun SqlBuilder.userIdEqualsTo(userId: Int) {
            addUnsafe("users.user_id = ${bind(userId)}")
        }

        val result: User = kueryClient
            .sql {
                +"SELECT * FROM users"
                +"WHERE"
                userIdEqualsTo(1)
            }
            .single()
        assertThat(result).isEqualTo(User(userId = 1, username = "user1", email = "user1@example.com"))
    }
}
