package dev.hsbrysk.kuery.spring.testing.contract.usage

import assertk.assertThat
import assertk.assertions.hasSize
import dev.hsbrysk.kuery.core.KueryClient
import dev.hsbrysk.kuery.spring.testing.ContractDatabase
import kotlinx.coroutines.test.runTest
import org.junit.jupiter.api.AfterEach
import org.junit.jupiter.api.BeforeEach
import org.junit.jupiter.api.Test

/**
 * Contract shared by the jdbc and r2dbc modules. Each module runs it via a concrete subclass
 * that supplies its `ContractDatabase`.
 *
 * Only `fetchSize` exists on both implementations; the blocking-only options (`maxRows`,
 * `queryTimeoutSeconds`) and option immutability (whose observable lever differs per module)
 * are tested on the concrete subclasses.
 */
abstract class StatementOptionsContract {
    protected abstract val database: ContractDatabase

    // lazy: `database` is not resolvable yet while this base class initializes.
    protected val kueryClient: KueryClient by lazy { database.kueryClient() }

    @BeforeEach
    fun setUpUsersTable() {
        database.execute(
            """
            CREATE TABLE users (
                user_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                username VARCHAR(50) NOT NULL,
                email VARCHAR(100) NOT NULL
            )
            """.trimIndent(),
        )
        repeat(10) { i ->
            database.execute("INSERT INTO users (username, email) VALUES ('user$i', 'user$i@example.com')")
        }
    }

    @AfterEach
    fun dropUsersTable() {
        database.execute("DROP TABLE IF EXISTS users")
    }

    @Test
    fun `fetchSize does not break results`() = runTest {
        val result = kueryClient.sql { +"SELECT * FROM users" }
            .fetchSize(3)
            .listMap()
        assertThat(result).hasSize(10)
    }
}
