package dev.hsbrysk.kuery.spring.testing.contract.usage

import assertk.assertThat
import assertk.assertions.isEqualTo
import dev.hsbrysk.kuery.core.KueryClient
import dev.hsbrysk.kuery.core.list
import dev.hsbrysk.kuery.core.values
import dev.hsbrysk.kuery.spring.testing.ContractDatabase
import kotlinx.coroutines.test.runTest
import org.junit.jupiter.api.AfterEach
import org.junit.jupiter.api.BeforeEach
import org.junit.jupiter.api.Test

/**
 * Contract shared by the jdbc and r2dbc modules. Each module runs it via a concrete subclass
 * that supplies its `ContractDatabase`.
 */
abstract class ValuesHelperContract {
    protected abstract val database: ContractDatabase

    // lazy: `database` is not resolvable yet while this base class initializes.
    protected val kueryClient: KueryClient by lazy { database.kueryClient() }

    @BeforeEach
    fun setUpUsersTable() {
        database.execute(
            """
            CREATE TABLE users (
                user_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                username VARCHAR(50) NOT NULL,
                email VARCHAR(100),
                age INT NOT NULL
            )
            """.trimIndent(),
        )
    }

    @AfterEach
    fun dropUsersTable() {
        database.execute("DROP TABLE IF EXISTS users")
    }

    data class User(
        val userId: Int,
        val username: String,
        val email: String?,
        val age: Int,
    )

    @Test
    fun `values expands a list of rows into a multi-row INSERT`() = runTest {
        // given
        val input = listOf(
            listOf("user1", "user1@example.com", 1),
            listOf("user2", null, 2),
            listOf("user3", "user3@example.com", 3),
        )

        // when & then
        val rowsUpdated = kueryClient.sql {
            +"INSERT INTO users (username, email, age)"
            values(input)
        }.rowsUpdated()
        assertThat(rowsUpdated).isEqualTo(3)

        val users: List<User> = kueryClient.sql {
            +"SELECT * FROM users"
        }.list()
        assertThat(users).isEqualTo(
            listOf(
                User(1, "user1", "user1@example.com", 1),
                User(2, "user2", null, 2),
                User(3, "user3", "user3@example.com", 3),
            ),
        )
    }

    @Test
    fun `values with a transformer maps objects to rows before binding`() = runTest {
        data class UserParam(
            val username: String,
            val email: String?,
            val age: Int,
        )

        // given
        val input = listOf(
            UserParam("user1", "user1@example.com", 1),
            UserParam("user2", null, 2),
            UserParam("user3", "user3@example.com", 3),
        )

        // when & then
        val rowsUpdated = kueryClient.sql {
            +"INSERT INTO users (username, email, age)"
            values(input) { listOf(it.username, it.email, it.age) }
        }.rowsUpdated()
        assertThat(rowsUpdated).isEqualTo(3)

        val users: List<User> = kueryClient.sql {
            +"SELECT * FROM users"
        }.list()
        assertThat(users).isEqualTo(
            listOf(
                User(1, "user1", "user1@example.com", 1),
                User(2, "user2", null, 2),
                User(3, "user3", "user3@example.com", 3),
            ),
        )
    }
}
