package dev.hsbrysk.kuery.sqlx4k

import dev.hsbrysk.kuery.core.Sql
import dev.hsbrysk.kuery.core.SqlBuilder
import io.github.smyrgeorge.sqlx4k.QueryExecutor
import io.github.smyrgeorge.sqlx4k.ResultSet
import io.github.smyrgeorge.sqlx4k.RowMapper
import io.github.smyrgeorge.sqlx4k.Statement
import kotlin.reflect.KClass

/**
 * PoC: minimal KueryClient-like facade backed by a sqlx4k [QueryExecutor].
 *
 * Deliberate subset compared to the Spring-backed clients:
 * - no Micrometer observation (decided out of scope for the sqlx4k backend)
 * - no `flow()` / `generatedValues()` — sqlx4k has neither row streaming nor a
 *   generated-keys API
 * - row mapping is an explicit `(ResultSet.Row) -> T` function; Kotlin/Native has no
 *   kotlin-reflect, so the reflection-based data-class mapping of the Spring backends
 *   cannot exist here
 */
public class Sqlx4kKueryClient(private val executor: QueryExecutor) {
    public fun sql(block: SqlBuilder.() -> Unit): Sqlx4kFetchSpec = Sqlx4kFetchSpec(executor, Sql(block))
}

public class Sqlx4kFetchSpec internal constructor(
    private val executor: QueryExecutor,
    private val sql: Sql,
) {
    // single/singleOrNull decide on the ROW count before mapping — a mapper may legitimately
    // return null (e.g. a nullable column), which must not be confused with "no rows".
    public suspend fun <T> single(mapper: (ResultSet.Row) -> T): T {
        val rows = rows()
        if (rows.isEmpty()) throw NoSuchElementException("Expected exactly one row, but none matched.")
        check(rows.size == 1) { "Expected exactly one row, but ${rows.size} rows matched." }
        return mapper(rows.single())
    }

    public suspend fun <T> singleOrNull(mapper: (ResultSet.Row) -> T): T? {
        val rows = rows()
        check(rows.size <= 1) { "Expected at most one row, but ${rows.size} rows matched." }
        return rows.firstOrNull()?.let(mapper)
    }

    public suspend fun <T> list(mapper: (ResultSet.Row) -> T): List<T> = rows().map(mapper)

    // sqlx4k-native mapping: accept sqlx4k's RowMapper directly (hand-written or generated by
    // sqlx4k-codegen from a @Table entity) and delegate to the driver's mapped fetchAll, which
    // also supplies the driver's ValueEncoderRegistry.
    public suspend fun <T> single(mapper: RowMapper<T>): T {
        val items = list(mapper)
        if (items.isEmpty()) throw NoSuchElementException("Expected exactly one row, but none matched.")
        check(items.size == 1) { "Expected exactly one row, but ${items.size} rows matched." }
        return items.single()
    }

    public suspend fun <T> singleOrNull(mapper: RowMapper<T>): T? {
        val items = list(mapper)
        check(items.size <= 1) { "Expected at most one row, but ${items.size} rows matched." }
        return items.firstOrNull()
    }

    public suspend fun <T> list(mapper: RowMapper<T>): List<T> =
        executor.fetchAll(statement(), mapper).getOrThrow()

    // Compiler-plugin mapping (the fourth PoC stage): `.list<User>()` — no annotation, no KSP,
    // no reflection. The plugin synthesizes the (Row) -> T mapper from the reified type argument
    // and rewrites the call to the lambda overloads above. Without the plugin these markers
    // throw at runtime, mirroring the add/unaryPlus design. The KClass variants exist because
    // the inline wrappers may already be inlined when the IR pass runs (backend-dependent);
    // the plugin recognizes both shapes.
    public suspend inline fun <reified T : Any> single(): T = single(T::class)

    public suspend inline fun <reified T : Any> singleOrNull(): T? = singleOrNull(T::class)

    public suspend inline fun <reified T : Any> list(): List<T> = list(T::class)

    public suspend fun <T : Any> single(type: KClass<T>): T = injectedByPlugin(type)

    public suspend fun <T : Any> singleOrNull(type: KClass<T>): T? = injectedByPlugin(type)

    public suspend fun <T : Any> list(type: KClass<T>): List<T> = injectedByPlugin(type)

    private fun injectedByPlugin(type: KClass<*>): Nothing = error(
        "`Sqlx4kFetchSpec.single/singleOrNull/list<${type.simpleName}>()` must be rewritten by the " +
            "kuery-client compiler plugin (PoC), but this call was not. Make sure the plugin is applied.",
    )

    private suspend fun rows(): List<ResultSet.Row> = executor.fetchAll(statement()).getOrThrow().toList()

    public suspend fun rowsUpdated(): Long = executor.execute(statement()).getOrThrow()

    /**
     * Bridges the core abstraction to sqlx4k: [Sql.body] already contains `:pN` placeholders,
     * which is exactly sqlx4k's named-parameter syntax, so the conversion is a plain rebind.
     */
    private fun statement(): Statement {
        var statement = Statement.create(sql.body)
        for (parameter in sql.parameters) {
            statement = statement.bind(parameter.name, parameter.value)
        }
        return statement
    }
}
