package dev.hsbrysk.kuery.spring.r2dbc.sqlid

import assertk.assertThat
import assertk.assertions.containsExactly
import com.example.spring.r2dbc.UserRepository
import dev.hsbrysk.kuery.spring.r2dbc.H2TestDatabase
import dev.hsbrysk.kuery.spring.r2dbc.SpringR2dbcKueryClient
import kotlinx.coroutines.flow.collect
import kotlinx.coroutines.test.runTest
import org.junit.jupiter.api.AfterEach
import org.junit.jupiter.api.BeforeEach
import org.junit.jupiter.api.Test
import org.springframework.r2dbc.core.awaitRowsUpdated
import java.util.concurrent.CopyOnWriteArrayList

class SqlIdReactorContextTest {
    private val capturedSqlIds = CopyOnWriteArrayList<String?>()
    private val kueryClient = SpringR2dbcKueryClient.builder()
        .connectionFactory(SqlIdCapturingConnectionFactory(h2.connectionFactory, capturedSqlIds))
        .enableAutoSqlIdGeneration(true)
        .build()
    private val userRepository = UserRepository(kueryClient)

    @BeforeEach
    fun setUp() = runTest {
        h2.databaseClient.sql(
            """
            CREATE TABLE users (
                user_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                username VARCHAR(50) NOT NULL,
                email VARCHAR(100) NOT NULL
            )
            """.trimIndent(),
        ).fetch().awaitRowsUpdated()
        h2.databaseClient.sql(
            """
            INSERT INTO users (username, email) VALUES
            ('user1', 'user1@example.com'),
            ('user2', 'user2@example.com')
            """.trimIndent(),
        ).fetch().awaitRowsUpdated()
        capturedSqlIds.clear()
    }

    @AfterEach
    fun tearDown() = runTest {
        h2.databaseClient.sql("DROP TABLE users").fetch().awaitRowsUpdated()
    }

    @Test
    fun `singleMap propagates the auto-generated sqlId to statement execution`() = runTest {
        userRepository.singleMap(1)
        assertThat(capturedSqlIds).containsExactly("com.example.spring.r2dbc.UserRepository.singleMap")
    }

    @Test
    fun `singleMapOrNull propagates the auto-generated sqlId to statement execution`() = runTest {
        userRepository.singleMapOrNull(1)
        assertThat(capturedSqlIds).containsExactly("com.example.spring.r2dbc.UserRepository.singleMapOrNull")
    }

    @Test
    fun `single propagates the auto-generated sqlId to statement execution`() = runTest {
        userRepository.single(1)
        assertThat(capturedSqlIds).containsExactly("com.example.spring.r2dbc.UserRepository.single")
    }

    @Test
    fun `singleOrNull propagates the auto-generated sqlId to statement execution`() = runTest {
        userRepository.singleOrNull(1)
        assertThat(capturedSqlIds).containsExactly("com.example.spring.r2dbc.UserRepository.singleOrNull")
    }

    @Test
    fun `listMap propagates the auto-generated sqlId to statement execution`() = runTest {
        userRepository.listMap()
        assertThat(capturedSqlIds).containsExactly("com.example.spring.r2dbc.UserRepository.listMap")
    }

    @Test
    fun `list propagates the auto-generated sqlId to statement execution`() = runTest {
        userRepository.list()
        assertThat(capturedSqlIds).containsExactly("com.example.spring.r2dbc.UserRepository.list")
    }

    @Test
    fun `flowMap propagates the auto-generated sqlId to statement execution`() = runTest {
        userRepository.flowMap().collect()
        assertThat(capturedSqlIds).containsExactly("com.example.spring.r2dbc.UserRepository.flowMap")
    }

    @Test
    fun `flow propagates the auto-generated sqlId to statement execution`() = runTest {
        userRepository.flow().collect()
        assertThat(capturedSqlIds).containsExactly("com.example.spring.r2dbc.UserRepository.flow")
    }

    @Test
    fun `rowsUpdated propagates the auto-generated sqlId to statement execution`() = runTest {
        userRepository.rowUpdated("user3", "user3@example.com")
        assertThat(capturedSqlIds).containsExactly("com.example.spring.r2dbc.UserRepository.rowUpdated")
    }

    @Test
    fun `generatedValues propagates the auto-generated sqlId to statement execution`() = runTest {
        userRepository.generatedValues("user3", "user3@example.com")
        assertThat(capturedSqlIds).containsExactly("com.example.spring.r2dbc.UserRepository.generatedValues")
    }

    companion object {
        private val h2 = H2TestDatabase()
    }
}
