package dev.hsbrysk.kuery.spring.r2dbc.sqlid

import assertk.assertThat
import assertk.assertions.containsExactly
import com.example.spring.r2dbc.UserRepository
import dev.hsbrysk.kuery.spring.r2dbc.H2TestDatabase
import dev.hsbrysk.kuery.spring.r2dbc.SpringR2dbcKueryClient
import io.micrometer.observation.tck.TestObservationRegistry
import kotlinx.coroutines.test.runTest
import org.junit.jupiter.api.AfterEach
import org.junit.jupiter.api.BeforeEach
import org.junit.jupiter.api.Test
import org.springframework.r2dbc.core.awaitRowsUpdated
import java.util.concurrent.CopyOnWriteArrayList

/**
 * Pins the builder's default rule for auto sqlId generation: it follows whether an
 * observationRegistry is set, and an explicit enableAutoSqlIdGeneration always wins.
 */
class SqlIdGenerationDefaultTest {
    private val capturedSqlIds = CopyOnWriteArrayList<String?>()

    @BeforeEach
    fun setUp() = runTest {
        h2.databaseClient.sql(
            """
            CREATE TABLE users (
                user_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                username VARCHAR(50) NOT NULL,
                email VARCHAR(100) NOT NULL
            )
            """.trimIndent(),
        ).fetch().awaitRowsUpdated()
        h2.databaseClient.sql("INSERT INTO users (username, email) VALUES ('user1', 'user1@example.com')")
            .fetch().awaitRowsUpdated()
        capturedSqlIds.clear()
    }

    @AfterEach
    fun tearDown() = runTest {
        h2.databaseClient.sql("DROP TABLE users").fetch().awaitRowsUpdated()
    }

    @Test
    fun `auto sqlId generation defaults to enabled when an observationRegistry is set`() = runTest {
        val kueryClient = SpringR2dbcKueryClient.builder()
            .connectionFactory(SqlIdCapturingConnectionFactory(h2.connectionFactory, capturedSqlIds))
            .observationRegistry(TestObservationRegistry.create())
            .build()

        UserRepository(kueryClient).singleMap(1)

        assertThat(capturedSqlIds).containsExactly("com.example.spring.r2dbc.UserRepository.singleMap")
    }

    @Test
    fun `auto sqlId generation defaults to disabled without an observationRegistry`() = runTest {
        val kueryClient = SpringR2dbcKueryClient.builder()
            .connectionFactory(SqlIdCapturingConnectionFactory(h2.connectionFactory, capturedSqlIds))
            .build()

        UserRepository(kueryClient).singleMap(1)

        assertThat(capturedSqlIds).containsExactly("NONE")
    }

    @Test
    fun `explicit false disables auto sqlId generation even with an observationRegistry`() = runTest {
        val kueryClient = SpringR2dbcKueryClient.builder()
            .connectionFactory(SqlIdCapturingConnectionFactory(h2.connectionFactory, capturedSqlIds))
            .observationRegistry(TestObservationRegistry.create())
            .enableAutoSqlIdGeneration(false)
            .build()

        UserRepository(kueryClient).singleMap(1)

        assertThat(capturedSqlIds).containsExactly("NONE")
    }

    companion object {
        private val h2 = H2TestDatabase()
    }
}
