package dev.hsbrysk.kuery.spring.r2dbc.mapping

import assertk.assertThat
import assertk.assertions.isEqualTo
import dev.hsbrysk.kuery.core.single
import dev.hsbrysk.kuery.spring.r2dbc.H2TestDatabase
import kotlinx.coroutines.test.runTest
import org.junit.jupiter.api.AfterEach
import org.junit.jupiter.api.BeforeEach
import org.junit.jupiter.api.Test
import org.springframework.r2dbc.core.awaitRowsUpdated

class ColumnNameCaseMappingTest {
    private val kueryClient = h2.kueryClient()

    @BeforeEach
    fun beforeEach() = runTest {
        h2.databaseClient.sql(
            """
            CREATE TABLE string_case
            (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                hoge_bar VARCHAR(255) DEFAULT NULL,
                fugaPiyo VARCHAR(255) DEFAULT NULL
            )
            """.trimIndent(),
        ).fetch().awaitRowsUpdated()
    }

    @AfterEach
    fun afterEach() = runTest {
        h2.databaseClient.sql("DROP TABLE string_case").fetch().awaitRowsUpdated()
    }

    data class Record(
        val hogeBar: String,
        val fugaPiyo: String,
    )

    @Test
    fun `snake_case and camelCase columns both map to data class properties`() = runTest {
        // given
        kueryClient.sql {
            +"INSERT INTO string_case (hoge_bar, fugaPiyo) VALUES ('a', 'b')"
        }.rowsUpdated()

        // when
        val record: Record = kueryClient.sql {
            +"SELECT * FROM string_case"
        }.single()
        println(record)

        // then
        assertThat(record.hogeBar).isEqualTo("a")
        assertThat(record.fugaPiyo).isEqualTo("b")
    }

    companion object {
        private val h2 = H2TestDatabase()
    }
}
