package dev.hsbrysk.kuery.spring.r2dbc.mapping

import assertk.assertFailure
import assertk.assertThat
import assertk.assertions.isEqualTo
import assertk.assertions.isInstanceOf
import dev.hsbrysk.kuery.core.single
import dev.hsbrysk.kuery.spring.r2dbc.H2TestDatabase
import kotlinx.coroutines.test.runTest
import org.junit.jupiter.api.AfterEach
import org.junit.jupiter.api.BeforeEach
import org.junit.jupiter.api.Test
import org.springframework.dao.DataRetrievalFailureException
import org.springframework.r2dbc.core.awaitRowsUpdated

class DataClassColumnMismatchTest {
    private val kueryClient = h2.kueryClient()

    @BeforeEach
    fun beforeEach() = runTest {
        h2.databaseClient.sql(
            """
            CREATE TABLE person
            (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                name VARCHAR(255) NOT NULL,
                nickname VARCHAR(255) DEFAULT NULL
            )
            """.trimIndent(),
        ).fetch().awaitRowsUpdated()
        h2.databaseClient.sql("INSERT INTO person (name, nickname) VALUES ('alice', 'ali')")
            .fetch().awaitRowsUpdated()
    }

    @AfterEach
    fun afterEach() = runTest {
        h2.databaseClient.sql("DROP TABLE person").fetch().awaitRowsUpdated()
    }

    data class NameOnly(val name: String)

    data class NameAndNickname(
        val name: String,
        val nickname: String?,
    )

    @Test
    fun `extra selected columns absent from the data class are ignored`() = runTest {
        val record: NameOnly = kueryClient.sql { +"SELECT * FROM person" }.single()
        assertThat(record).isEqualTo(NameOnly("alice"))
    }

    @Test
    fun `a missing column for a constructor parameter throws even if the property is nullable`() = runTest {
        // The jdbc module reports the same mismatch as BadSqlGrammarException instead.
        assertFailure {
            kueryClient.sql { +"SELECT name FROM person" }.single(NameAndNickname::class)
        }.isInstanceOf(DataRetrievalFailureException::class)
    }

    companion object {
        private val h2 = H2TestDatabase()
    }
}
