package dev.hsbrysk.kuery.spring.r2dbc.mapping

import assertk.assertThat
import assertk.assertions.isEqualTo
import dev.hsbrysk.kuery.spring.r2dbc.H2TestDatabase
import kotlinx.coroutines.test.runTest
import org.junit.jupiter.api.AfterEach
import org.junit.jupiter.api.BeforeEach
import org.junit.jupiter.api.Test
import org.springframework.r2dbc.core.awaitRowsUpdated

/**
 * Note the jdbc/r2dbc divergence: spring-r2dbc's column map keeps the LAST occurrence of a
 * duplicated label, while spring-jdbc's ColumnMapRowMapper keeps the FIRST. Alias duplicated
 * columns explicitly when joining tables that share column names.
 */
class DuplicateColumnLabelTest {
    private val kueryClient = h2.kueryClient()

    @BeforeEach
    fun beforeEach() = runTest {
        h2.databaseClient.sql(
            """
            CREATE TABLE person
            (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                name VARCHAR(255) NOT NULL,
                company_id BIGINT NOT NULL
            )
            """.trimIndent(),
        ).fetch().awaitRowsUpdated()
        h2.databaseClient.sql(
            """
            CREATE TABLE company
            (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                name VARCHAR(255) NOT NULL
            )
            """.trimIndent(),
        ).fetch().awaitRowsUpdated()
        h2.databaseClient.sql("INSERT INTO company (id, name) VALUES (1, 'acme')").fetch().awaitRowsUpdated()
        h2.databaseClient.sql("INSERT INTO person (name, company_id) VALUES ('alice', 1)")
            .fetch().awaitRowsUpdated()
    }

    @AfterEach
    fun afterEach() = runTest {
        h2.databaseClient.sql("DROP TABLE person").fetch().awaitRowsUpdated()
        h2.databaseClient.sql("DROP TABLE company").fetch().awaitRowsUpdated()
    }

    @Test
    fun `singleMap keeps the last value when a join produces duplicate column labels`() = runTest {
        val record = kueryClient.sql {
            +"""
            SELECT person.name, company.name
            FROM person
            JOIN company ON person.company_id = company.id
            """.trimIndent()
        }.singleMap()

        assertThat(record["name"]).isEqualTo("acme")
    }

    companion object {
        private val h2 = H2TestDatabase()
    }
}
