package dev.hsbrysk.kuery.spring.r2dbc.usage

import assertk.assertFailure
import assertk.assertThat
import assertk.assertions.isEqualTo
import assertk.assertions.isNotEmpty
import assertk.assertions.isTrue
import dev.hsbrysk.kuery.core.flow
import dev.hsbrysk.kuery.spring.r2dbc.H2TestDatabase
import dev.hsbrysk.kuery.spring.r2dbc.SpringR2dbcKueryClient
import io.r2dbc.spi.Connection
import io.r2dbc.spi.ConnectionFactory
import kotlinx.coroutines.CompletableDeferred
import kotlinx.coroutines.awaitCancellation
import kotlinx.coroutines.flow.first
import kotlinx.coroutines.flow.toList
import kotlinx.coroutines.launch
import kotlinx.coroutines.test.runTest
import org.junit.jupiter.api.AfterEach
import org.junit.jupiter.api.BeforeEach
import org.junit.jupiter.api.Test
import org.reactivestreams.Publisher
import org.springframework.r2dbc.core.awaitRowsUpdated
import reactor.core.publisher.Mono
import java.util.concurrent.CopyOnWriteArrayList
import java.util.concurrent.CountDownLatch
import java.util.concurrent.TimeUnit

/**
 * flow()/flowMap() must release the connection no matter how the collection ends. The jdbc module
 * pins the same contract for sequence() in SequenceResourceManagementTest.
 */
class FlowResourceManagementTest {
    private val kueryClient = SpringR2dbcKueryClient.builder()
        .connectionFactory(trackingConnectionFactory)
        .build()

    @BeforeEach
    fun beforeEach() = runTest {
        h2.databaseClient.sql(
            """
            CREATE TABLE users (
                user_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                username VARCHAR(50) NOT NULL
            )
            """.trimIndent(),
        ).fetch().awaitRowsUpdated()
        h2.databaseClient.sql("INSERT INTO users (username) VALUES ('user1'), ('user2')")
            .fetch().awaitRowsUpdated()
        trackingConnectionFactory.connections.clear()
    }

    @AfterEach
    fun afterEach() = runTest {
        h2.databaseClient.sql("DROP TABLE users").fetch().awaitRowsUpdated()
    }

    @Test
    fun `flow releases the connection after full collection`() = runTest {
        // when
        val result: List<User> = kueryClient.sql { +"SELECT * FROM users" }.flow<User>().toList()

        // then
        assertThat(result).isEqualTo(
            listOf(
                User(userId = 1, username = "user1"),
                User(userId = 2, username = "user2"),
            ),
        )
        assertAllTrackedConnectionsClosed()
    }

    @Test
    fun `flowMap releases the connection after full collection`() = runTest {
        // when
        val result = kueryClient.sql { +"SELECT * FROM users" }.flowMap().toList()

        // then
        assertThat(result).isEqualTo(
            listOf(
                mapOf("user_id" to 1, "username" to "user1"),
                mapOf("user_id" to 2, "username" to "user2"),
            ),
        )
        assertAllTrackedConnectionsClosed()
    }

    @Test
    fun `flow releases the connection when only the first element is collected`() = runTest {
        // when
        val result = kueryClient.sql { +"SELECT * FROM users" }.flow<User>().first()

        // then
        assertThat(result).isEqualTo(User(userId = 1, username = "user1"))
        assertAllTrackedConnectionsClosed()
    }

    @Test
    fun `flow releases the connection when row mapping fails`() = runTest {
        assertFailure {
            kueryClient.sql { +"SELECT username FROM users" }.flow<Int>().toList()
        }
        assertAllTrackedConnectionsClosed()
    }

    @Test
    fun `flow releases the connection when the collecting coroutine is cancelled`() = runTest {
        // given
        val collectionStarted = CompletableDeferred<Unit>()
        val job = launch {
            kueryClient.sql { +"SELECT * FROM users" }.flow<User>().collect {
                collectionStarted.complete(Unit)
                awaitCancellation()
            }
        }

        // when
        collectionStarted.await()
        job.cancel()
        job.join()

        // then
        assertAllTrackedConnectionsClosed()
    }

    private fun assertAllTrackedConnectionsClosed() {
        assertThat(trackingConnectionFactory.connections).isNotEmpty()
        trackingConnectionFactory.connections.forEach {
            assertThat(it.awaitClosed()).isTrue()
        }
    }

    data class User(
        val userId: Int,
        val username: String,
    )

    private class TrackingConnectionFactory(private val delegate: ConnectionFactory) : ConnectionFactory by delegate {
        val connections = CopyOnWriteArrayList<TrackingConnection>()

        override fun create(): Publisher<out Connection> = Mono.from(delegate.create())
            .map { TrackingConnection(it).also(connections::add) }
    }

    private class TrackingConnection(private val delegate: Connection) : Connection by delegate {
        // Cleanup after a cancelled collection happens asynchronously, so closing must be awaited.
        private val closeLatch = CountDownLatch(1)

        @Suppress("ForbiddenVoid") // the R2DBC SPI mandates Publisher<Void> for close()
        override fun close(): Publisher<Void> = Mono.from(delegate.close())
            .doOnSuccess { closeLatch.countDown() }

        fun awaitClosed(): Boolean = closeLatch.await(5, TimeUnit.SECONDS)
    }

    companion object {
        private val h2 = H2TestDatabase()
        private val trackingConnectionFactory = TrackingConnectionFactory(h2.connectionFactory)
    }
}
