package dev.hsbrysk.kuery.spring.testing.contract.mapping

import assertk.assertThat
import assertk.assertions.isEqualTo
import dev.hsbrysk.kuery.core.KueryClient
import dev.hsbrysk.kuery.core.single
import dev.hsbrysk.kuery.spring.testing.ContractDatabase
import kotlinx.coroutines.test.runTest
import org.junit.jupiter.api.AfterEach
import org.junit.jupiter.api.BeforeEach
import org.junit.jupiter.api.Test

/**
 * Contract shared by the jdbc and r2dbc modules. Each module runs it via a concrete subclass
 * that supplies its `ContractDatabase`.
 */
abstract class ColumnNameCaseMappingContract {
    protected abstract val database: ContractDatabase

    // lazy: `database` is not resolvable yet while this base class initializes.
    protected val kueryClient: KueryClient by lazy { database.kueryClient() }

    @BeforeEach
    fun setUpStringCaseTable() {
        database.execute(
            """
            CREATE TABLE string_case
            (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                hoge_bar VARCHAR(255) DEFAULT NULL,
                fugaPiyo VARCHAR(255) DEFAULT NULL
            )
            """.trimIndent(),
        )
    }

    @AfterEach
    fun dropStringCaseTable() {
        database.execute("DROP TABLE IF EXISTS string_case")
    }

    data class Record(
        val hogeBar: String,
        val fugaPiyo: String,
    )

    @Test
    fun `snake_case and camelCase columns both map to data class properties`() = runTest {
        // given
        kueryClient.sql {
            +"INSERT INTO string_case (hoge_bar, fugaPiyo) VALUES ('a', 'b')"
        }.rowsUpdated()

        // when
        val record: Record = kueryClient.sql {
            +"SELECT * FROM string_case"
        }.single()

        // then
        assertThat(record.hogeBar).isEqualTo("a")
        assertThat(record.fugaPiyo).isEqualTo("b")
    }
}
