package dev.hsbrysk.kuery.spring.testing.contract.mapping

import assertk.assertFailure
import assertk.assertThat
import assertk.assertions.isEqualTo
import assertk.assertions.isInstanceOf
import dev.hsbrysk.kuery.core.KueryClient
import dev.hsbrysk.kuery.core.single
import dev.hsbrysk.kuery.spring.testing.ContractDatabase
import dev.hsbrysk.kuery.spring.testing.ExceptionProfile
import kotlinx.coroutines.test.runTest
import org.junit.jupiter.api.AfterEach
import org.junit.jupiter.api.BeforeEach
import org.junit.jupiter.api.Test

/**
 * Contract shared by the jdbc and r2dbc modules. Each module runs it via a concrete subclass
 * that supplies its `ContractDatabase`.
 */
abstract class DataClassColumnMismatchContract {
    protected abstract val database: ContractDatabase

    protected abstract val exceptionProfile: ExceptionProfile

    // lazy: `database` is not resolvable yet while this base class initializes.
    protected val kueryClient: KueryClient by lazy { database.kueryClient() }

    @BeforeEach
    fun setUpPersonTable() {
        database.execute(
            """
            CREATE TABLE person
            (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                name VARCHAR(255) NOT NULL,
                nickname VARCHAR(255) DEFAULT NULL
            )
            """.trimIndent(),
        )
        database.execute("INSERT INTO person (name, nickname) VALUES ('alice', 'ali')")
    }

    @AfterEach
    fun dropPersonTable() {
        database.execute("DROP TABLE IF EXISTS person")
    }

    data class NameOnly(val name: String)

    data class NameAndNickname(
        val name: String,
        val nickname: String?,
    )

    @Test
    fun `extra selected columns absent from the data class are ignored`() = runTest {
        val record: NameOnly = kueryClient.sql { +"SELECT * FROM person" }.single()
        assertThat(record).isEqualTo(NameOnly("alice"))
    }

    @Test
    fun `a missing column for a constructor parameter throws even if the property is nullable`() = runTest {
        // The concrete exception type is module-specific; each module's ExceptionProfile
        // documents why.
        assertFailure {
            kueryClient.sql { +"SELECT name FROM person" }.single(NameAndNickname::class)
        }.isInstanceOf(exceptionProfile.columnMismatchException)
    }
}
