package dev.hsbrysk.kuery.spring.testing.contract.mapping

import dev.hsbrysk.kuery.core.KueryClient
import dev.hsbrysk.kuery.spring.testing.ContractDatabase
import org.junit.jupiter.api.AfterEach
import org.junit.jupiter.api.BeforeEach

/**
 * Setup for the duplicate-column-label scenario. Which occurrence of a duplicated label wins is
 * module-specific (spring-jdbc's ColumnMapRowMapper keeps the FIRST, spring-r2dbc's column map
 * keeps the LAST), so the test itself lives on each concrete subclass; only the setup and the
 * query are shared here.
 */
abstract class DuplicateColumnLabelContract {
    protected abstract val database: ContractDatabase

    // lazy: `database` is not resolvable yet while this base class initializes.
    protected val kueryClient: KueryClient by lazy { database.kueryClient() }

    @BeforeEach
    fun setUpJoinTables() {
        database.execute(
            """
            CREATE TABLE person
            (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                name VARCHAR(255) NOT NULL,
                company_id BIGINT NOT NULL
            )
            """.trimIndent(),
        )
        database.execute(
            """
            CREATE TABLE company
            (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                name VARCHAR(255) NOT NULL
            )
            """.trimIndent(),
        )
        database.execute("INSERT INTO company (id, name) VALUES (1, 'acme')")
        database.execute("INSERT INTO person (name, company_id) VALUES ('alice', 1)")
    }

    @AfterEach
    fun dropJoinTables() {
        database.execute("DROP TABLE IF EXISTS person")
        database.execute("DROP TABLE IF EXISTS company")
    }

    /** Joins person ('alice') and company ('acme') so the result holds two `name` columns. */
    protected suspend fun singleMapWithDuplicateLabels(): Map<String, Any?> = kueryClient.sql {
        +"""
        SELECT person.name, company.name
        FROM person
        JOIN company ON person.company_id = company.id
        """.trimIndent()
    }.singleMap()
}
