package dev.hsbrysk.kuery.spring.jdbc.sqlid

import assertk.assertThat
import assertk.assertions.containsExactly
import com.example.spring.jdbc.UserRepository
import dev.hsbrysk.kuery.spring.jdbc.H2TestDatabase
import dev.hsbrysk.kuery.spring.jdbc.SpringJdbcKueryClient
import org.junit.jupiter.api.AfterEach
import org.junit.jupiter.api.BeforeEach
import org.junit.jupiter.api.Test

class SqlIdThreadLocalTest {
    private val capturedSqlIds = mutableListOf<String?>()
    private val kueryClient = SpringJdbcKueryClient.builder()
        .dataSource(SqlIdCapturingDataSource(h2.dataSource, capturedSqlIds))
        .enableAutoSqlIdGeneration(true)
        .build()
    private val userRepository = UserRepository(kueryClient)

    @BeforeEach
    fun setUp() {
        h2.jdbcClient.sql(
            """
            CREATE TABLE users (
                user_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                username VARCHAR(50) NOT NULL,
                email VARCHAR(100) NOT NULL
            )
            """.trimIndent(),
        ).update()
        h2.jdbcClient.sql(
            """
            INSERT INTO users (username, email) VALUES
            ('user1', 'user1@example.com'),
            ('user2', 'user2@example.com')
            """.trimIndent(),
        ).update()
        capturedSqlIds.clear()
    }

    @AfterEach
    fun tearDown() {
        h2.jdbcClient.sql("DROP TABLE users").update()
    }

    @Test
    fun `singleMap propagates the auto-generated sqlId to statement execution`() {
        userRepository.singleMap(1)
        assertThat(capturedSqlIds).containsExactly("com.example.spring.jdbc.UserRepository.singleMap")
    }

    @Test
    fun `singleMapOrNull propagates the auto-generated sqlId to statement execution`() {
        userRepository.singleMapOrNull(1)
        assertThat(capturedSqlIds).containsExactly("com.example.spring.jdbc.UserRepository.singleMapOrNull")
    }

    @Test
    fun `single propagates the auto-generated sqlId to statement execution`() {
        userRepository.single(1)
        assertThat(capturedSqlIds).containsExactly("com.example.spring.jdbc.UserRepository.single")
    }

    @Test
    fun `singleOrNull propagates the auto-generated sqlId to statement execution`() {
        userRepository.singleOrNull(1)
        assertThat(capturedSqlIds).containsExactly("com.example.spring.jdbc.UserRepository.singleOrNull")
    }

    @Test
    fun `listMap propagates the auto-generated sqlId to statement execution`() {
        userRepository.listMap()
        assertThat(capturedSqlIds).containsExactly("com.example.spring.jdbc.UserRepository.listMap")
    }

    @Test
    fun `list propagates the auto-generated sqlId to statement execution`() {
        userRepository.list()
        assertThat(capturedSqlIds).containsExactly("com.example.spring.jdbc.UserRepository.list")
    }

    @Test
    fun `sequenceMap propagates the auto-generated sqlId to statement execution`() {
        userRepository.sequenceMap().use { it.toList() }
        assertThat(capturedSqlIds).containsExactly("com.example.spring.jdbc.UserRepository.sequenceMap")
    }

    @Test
    fun `sequence propagates the auto-generated sqlId to statement execution`() {
        userRepository.sequence().use { it.toList() }
        assertThat(capturedSqlIds).containsExactly("com.example.spring.jdbc.UserRepository.sequence")
    }

    @Test
    fun `rowsUpdated propagates the auto-generated sqlId to statement execution`() {
        userRepository.rowUpdated("user3", "user3@example.com")
        assertThat(capturedSqlIds).containsExactly("com.example.spring.jdbc.UserRepository.rowUpdated")
    }

    @Test
    fun `generatedValues propagates the auto-generated sqlId to statement execution`() {
        userRepository.generatedValues("user3", "user3@example.com")
        assertThat(capturedSqlIds).containsExactly("com.example.spring.jdbc.UserRepository.generatedValues")
    }

    @Test
    fun `multiple calls in one method are disambiguated with a numbered suffix in source order`() {
        userRepository.userAndCount(1)
        assertThat(capturedSqlIds).containsExactly(
            "com.example.spring.jdbc.UserRepository.userAndCount#1",
            "com.example.spring.jdbc.UserRepository.userAndCount#2",
        )
    }

    companion object {
        private val h2 = H2TestDatabase()
    }
}
