package dev.hsbrysk.kuery.spring.jdbc.sqlid

import assertk.assertThat
import assertk.assertions.containsExactly
import com.example.spring.jdbc.UserRepository
import dev.hsbrysk.kuery.spring.jdbc.H2TestDatabase
import dev.hsbrysk.kuery.spring.jdbc.SpringJdbcKueryClient
import io.micrometer.observation.tck.TestObservationRegistry
import org.junit.jupiter.api.AfterEach
import org.junit.jupiter.api.BeforeEach
import org.junit.jupiter.api.Test

/**
 * Pins the builder's default rule for auto sqlId generation: it follows whether an
 * observationRegistry is set, and an explicit enableAutoSqlIdGeneration always wins.
 */
class SqlIdGenerationDefaultTest {
    private val capturedSqlIds = mutableListOf<String?>()

    @BeforeEach
    fun setUp() {
        h2.jdbcClient.sql(
            """
            CREATE TABLE users (
                user_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                username VARCHAR(50) NOT NULL,
                email VARCHAR(100) NOT NULL
            )
            """.trimIndent(),
        ).update()
        h2.jdbcClient.sql("INSERT INTO users (username, email) VALUES ('user1', 'user1@example.com')").update()
        capturedSqlIds.clear()
    }

    @AfterEach
    fun tearDown() {
        h2.jdbcClient.sql("DROP TABLE users").update()
    }

    @Test
    fun `auto sqlId generation defaults to enabled when an observationRegistry is set`() {
        val kueryClient = SpringJdbcKueryClient.builder()
            .dataSource(SqlIdCapturingDataSource(h2.dataSource, capturedSqlIds))
            .observationRegistry(TestObservationRegistry.create())
            .build()

        UserRepository(kueryClient).singleMap(1)

        assertThat(capturedSqlIds).containsExactly("com.example.spring.jdbc.UserRepository.singleMap")
    }

    @Test
    fun `auto sqlId generation defaults to disabled without an observationRegistry`() {
        val kueryClient = SpringJdbcKueryClient.builder()
            .dataSource(SqlIdCapturingDataSource(h2.dataSource, capturedSqlIds))
            .build()

        UserRepository(kueryClient).singleMap(1)

        assertThat(capturedSqlIds).containsExactly("NONE")
    }

    @Test
    fun `explicit false disables auto sqlId generation even with an observationRegistry`() {
        val kueryClient = SpringJdbcKueryClient.builder()
            .dataSource(SqlIdCapturingDataSource(h2.dataSource, capturedSqlIds))
            .observationRegistry(TestObservationRegistry.create())
            .enableAutoSqlIdGeneration(false)
            .build()

        UserRepository(kueryClient).singleMap(1)

        assertThat(capturedSqlIds).containsExactly("NONE")
    }

    companion object {
        private val h2 = H2TestDatabase()
    }
}
