package dev.hsbrysk.kuery.spring.jdbc

import dev.hsbrysk.kuery.core.KueryBlockingClient
import io.micrometer.observation.ObservationRegistry
import org.h2.jdbcx.JdbcDataSource
import org.springframework.jdbc.core.simple.JdbcClient
import java.util.UUID

/**
 * In-memory H2 database for tests that exercise Kuery Client's own layer (interpolation,
 * FetchSpec, converters, ...). Driver-dependent behavior is tested against real databases in the
 * `mysql` / `postgres` packages instead.
 *
 * `DATABASE_TO_UPPER=FALSE` + `CASE_INSENSITIVE_IDENTIFIERS=TRUE` makes H2 keep identifiers as
 * written while matching them case-insensitively, mirroring MySQL's behavior.
 */
class H2TestDatabase {
    val dataSource = JdbcDataSource().apply {
        setURL(
            "jdbc:h2:mem:${UUID.randomUUID()};" +
                "DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=FALSE;CASE_INSENSITIVE_IDENTIFIERS=TRUE",
        )
        user = "sa"
    }
    val jdbcClient: JdbcClient = JdbcClient.create(dataSource)

    fun kueryClient(
        converters: List<Any> = emptyList(),
        observationRegistry: ObservationRegistry? = null,
    ): KueryBlockingClient = SpringJdbcKueryClient.builder()
        .dataSource(dataSource)
        .converters(converters)
        .apply {
            observationRegistry?.let { observationRegistry(it) }
        }
        .build()

    fun setUpForConverterTest() {
        jdbcClient.sql(
            """
            CREATE TABLE converter
            (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                text VARCHAR(255) DEFAULT NULL
            )
            """.trimIndent(),
        ).update()
    }

    fun tearDownForConverterTest() {
        jdbcClient.sql("DROP TABLE converter").update()
    }
}
