package dev.hsbrysk.kuery.spring.jdbc

import assertk.assertFailure
import assertk.assertThat
import assertk.assertions.isEqualTo
import assertk.assertions.isInstanceOf
import com.example.spring.jdbc.UserRepository
import io.micrometer.observation.Observation
import io.micrometer.observation.ObservationHandler
import io.micrometer.observation.tck.TestObservationRegistry
import io.micrometer.observation.tck.TestObservationRegistryAssert
import org.junit.jupiter.api.AfterEach
import org.junit.jupiter.api.BeforeEach
import org.junit.jupiter.api.Test
import org.springframework.dao.DataAccessException
import org.springframework.dao.EmptyResultDataAccessException

class ObservationTest {
    private val registry = TestObservationRegistry.create()
    private val kueryClient = h2.kueryClient(observationRegistry = registry)
    private val userRepository = UserRepository(kueryClient)

    @BeforeEach
    fun setUp() {
        h2.jdbcClient.sql(
            """
            CREATE TABLE users (
                user_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                username VARCHAR(50) NOT NULL,
                email VARCHAR(100) NOT NULL
            )
            """.trimIndent(),
        ).update()
        h2.jdbcClient.sql(
            """
            INSERT INTO users (username, email) VALUES
            ('user1', 'user1@example.com'),
            ('user2', 'user2@example.com')
            """.trimIndent(),
        ).update()
    }

    @AfterEach
    fun tearDown() {
        h2.jdbcClient.sql(
            """
            DROP TABLE users;
            """.trimIndent(),
        ).update()
    }

    @Test
    fun `singleMap records an observation with sqlId and sql`() {
        userRepository.singleMap(1)
        assertObservation(
            sqlId = "com.example.spring.jdbc.UserRepository.singleMap",
            sql = "SELECT * FROM users WHERE user_id = :p0",
        )
    }

    @Test
    fun `singleMapOrNull records an observation with sqlId and sql`() {
        userRepository.singleMapOrNull(1)
        assertObservation(
            sqlId = "com.example.spring.jdbc.UserRepository.singleMapOrNull",
            sql = "SELECT * FROM users WHERE user_id = :p0",
        )
    }

    @Test
    fun `single records an observation with sqlId and sql`() {
        userRepository.single(1)
        assertObservation(
            sqlId = "com.example.spring.jdbc.UserRepository.single",
            sql = "SELECT * FROM users WHERE user_id = :p0",
        )
    }

    @Test
    fun `singleOrNull records an observation with sqlId and sql`() {
        userRepository.singleOrNull(1)
        assertObservation(
            sqlId = "com.example.spring.jdbc.UserRepository.singleOrNull",
            sql = "SELECT * FROM users WHERE user_id = :p0",
        )
    }

    @Test
    fun `listMap records an observation with sqlId and sql`() {
        userRepository.listMap()
        assertObservation(
            sqlId = "com.example.spring.jdbc.UserRepository.listMap",
            sql = "SELECT * FROM users",
        )
    }

    @Test
    fun `list records an observation with sqlId and sql`() {
        userRepository.list()
        assertObservation(
            sqlId = "com.example.spring.jdbc.UserRepository.list",
            sql = "SELECT * FROM users",
        )
    }

    @Test
    fun `rowsUpdated records an observation with sqlId and sql`() {
        userRepository.rowUpdated("user3", "user3@example.com")
        assertObservation(
            sqlId = "com.example.spring.jdbc.UserRepository.rowUpdated",
            sql = "INSERT INTO users (username, email) VALUES (:p0, :p1)",
        )
    }

    @Test
    fun `generatedValues records an observation with sqlId and sql`() {
        userRepository.generatedValues("user3", "user3@example.com")
        assertObservation(
            sqlId = "com.example.spring.jdbc.UserRepository.generatedValues",
            sql = "INSERT INTO users (username, email) VALUES (:p0, :p1)",
        )
    }

    @Test
    fun `explicit sqlId overload propagates to the observation`() {
        kueryClient.sql("my.explicit.sql.id") { +"SELECT * FROM users" }.listMap()
        assertObservation(
            sqlId = "my.explicit.sql.id",
            sql = "SELECT * FROM users",
        )
    }

    @Test
    fun `records error when single result is missing`() {
        assertFailure { userRepository.singleMap(999) }.isInstanceOf(EmptyResultDataAccessException::class)
        TestObservationRegistryAssert.assertThat(registry)
            .doesNotHaveAnyRemainingCurrentObservation()
            .hasObservationWithNameEqualTo("kuery.client.fetches")
            .that()
            .hasBeenStarted()
            .hasBeenStopped()
            .hasError()
    }

    @Test
    fun `records error when the sql execution fails`() {
        assertFailure {
            kueryClient.sql { +"SELECT * FROM missing_table" }.listMap()
        }.isInstanceOf(DataAccessException::class)
        TestObservationRegistryAssert.assertThat(registry)
            .doesNotHaveAnyRemainingCurrentObservation()
            .hasObservationWithNameEqualTo("kuery.client.fetches")
            .that()
            .hasBeenStarted()
            .hasBeenStopped()
            .hasError()
    }

    @Test
    fun `scope is closed before the observation is stopped`() {
        // The documented Micrometer lifecycle order: close the scope, then stop the observation.

        // given
        val events = mutableListOf<String>()
        val recordingRegistry = TestObservationRegistry.create().apply {
            observationConfig().observationHandler(object : ObservationHandler<Observation.Context> {
                override fun supportsContext(context: Observation.Context): Boolean = true

                override fun onScopeClosed(context: Observation.Context) {
                    events.add("scopeClosed")
                }

                override fun onStop(context: Observation.Context) {
                    events.add("stop")
                }
            })
        }
        val client = h2.kueryClient(observationRegistry = recordingRegistry)

        // when
        UserRepository(client).singleMap(1)

        // then
        assertThat(events).isEqualTo(listOf("scopeClosed", "stop"))
    }

    private fun assertObservation(
        sqlId: String,
        sql: String,
    ) {
        TestObservationRegistryAssert.assertThat(registry)
            .doesNotHaveAnyRemainingCurrentObservation()
            .hasObservationWithNameEqualTo("kuery.client.fetches")
            .that()
            .hasLowCardinalityKeyValue("sql.id", sqlId)
            .hasHighCardinalityKeyValue("sql", sql)
            .hasBeenStarted()
            .hasBeenStopped()
    }

    companion object {
        private val h2 = H2TestDatabase()
    }
}
