package dev.hsbrysk.kuery.spring.jdbc

import assertk.assertThat
import assertk.assertions.isEqualTo
import dev.hsbrysk.kuery.core.single
import org.junit.jupiter.api.AfterEach
import org.junit.jupiter.api.BeforeEach
import org.junit.jupiter.api.Test

class StringCaseTest {
    private val kueryClient = h2.kueryClient()

    @BeforeEach
    fun beforeEach() {
        h2.jdbcClient.sql(
            """
            CREATE TABLE string_case
            (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                hoge_bar VARCHAR(255) DEFAULT NULL,
                fugaPiyo VARCHAR(255) DEFAULT NULL
            )
            """.trimIndent(),
        ).update()
    }

    @AfterEach
    fun afterEach() {
        h2.jdbcClient.sql("DROP TABLE string_case").update()
    }

    data class Record(
        val hogeBar: String,
        val fugaPiyo: String,
    )

    @Test
    fun `snake_case and camelCase columns both map to data class properties`() {
        // given
        kueryClient.sql {
            +"INSERT INTO string_case (hoge_bar, fugaPiyo) VALUES ('a', 'b')"
        }.rowsUpdated()

        // when
        val record: Record = kueryClient.sql {
            +"SELECT * FROM string_case"
        }.single()
        println(record)

        // then
        assertThat(record.hogeBar).isEqualTo("a")
        assertThat(record.fugaPiyo).isEqualTo("b")
    }

    companion object {
        private val h2 = H2TestDatabase()
    }
}
